
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP75;

import GeneralizedHelicopter.*;

public class HPMDP75 extends AbstractProvingMDPHelicopter{

    public HPMDP75(){
	super();
        setWind0(-0.660172d);
    	setWind1(-0.593397d);
    }
}