
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP33;

import GeneralizedHelicopter.*;

public class HPMDP33 extends AbstractProvingMDPHelicopter{

    public HPMDP33(){
	super();
        setWind0(-0.300474d);
    	setWind1(0.933242d);
    }
}