
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP94;

import GeneralizedHelicopter.*;

public class HPMDP94 extends AbstractProvingMDPHelicopter{

    public HPMDP94(){
	super();
        setWind0(0.905134d);
    	setWind1(0.121942d);
    }
}