
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP52;

import GeneralizedHelicopter.*;

public class HPMDP52 extends AbstractProvingMDPHelicopter{

    public HPMDP52(){
	super();
        setWind0(-0.347004d);
    	setWind1(0.326676d);
    }
}