
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP57;

import GeneralizedHelicopter.*;

public class HPMDP57 extends AbstractProvingMDPHelicopter{

    public HPMDP57(){
	super();
        setWind0(0.111480d);
    	setWind1(-0.709140d);
    }
}