
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP58;

import GeneralizedHelicopter.*;

public class HPMDP58 extends AbstractProvingMDPHelicopter{

    public HPMDP58(){
	super();
        setWind0(0.957411d);
    	setWind1(-0.016304d);
    }
}