
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP71;

import GeneralizedHelicopter.*;

public class HPMDP71 extends AbstractProvingMDPHelicopter{

    public HPMDP71(){
	super();
        setWind0(0.339391d);
    	setWind1(0.536766d);
    }
}