
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP15;

import GeneralizedHelicopter.*;

public class HPMDP15 extends AbstractProvingMDPHelicopter{

    public HPMDP15(){
	super();
        setWind0(0.498471d);
    	setWind1(0.598713d);
    }
}