
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP4;

import GeneralizedHelicopter.*;

public class HPMDP4 extends AbstractProvingMDPHelicopter{

    public HPMDP4(){
	super();
        setWind0(-0.091526d);
    	setWind1(0.276980d);
    }
}