
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP98;

import GeneralizedHelicopter.*;

public class HPMDP98 extends AbstractProvingMDPHelicopter{

    public HPMDP98(){
	super();
        setWind0(0.045236d);
    	setWind1(-0.597935d);
    }
}