
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP40;

import GeneralizedHelicopter.*;

public class HPMDP40 extends AbstractProvingMDPHelicopter{

    public HPMDP40(){
	super();
        setWind0(-0.351509d);
    	setWind1(-0.172799d);
    }
}