
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP42;

import GeneralizedHelicopter.*;

public class HPMDP42 extends AbstractProvingMDPHelicopter{

    public HPMDP42(){
	super();
        setWind0(0.360581d);
    	setWind1(-0.849299d);
    }
}