import GenParamSamples

method1 = "setWind0"
method2 = "setWind1"

f = open('./src/GeneralizedHelicopter/GenHeliParamData.java','w')

f.write("""
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package GeneralizedHelicopter;

public class GenHeliParamData {

    void setParameters(int ParamSet, GeneralizedHelicopter thisEnvironment) {
        switch (ParamSet) {""")
for i in range(10):
	f.write("""
            case %d:
                thisEnvironment.%s(%fd);
                thisEnvironment.%s(%fd);
                break;""" % (i, method1, GenParamSamples.sampleP1(i), method2, GenParamSamples.sampleP2(i)))

f.write("""
            default:
                System.err.println("Invalid Parameter Set Requested ("+ParamSet+") : using Param Set 0");
                setParameters(0, thisEnvironment);
        }
    }
}""")
f.close()
