
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP20;

import GeneralizedHelicopter.*;

public class HPMDP20 extends AbstractProvingMDPHelicopter{

    public HPMDP20(){
	super();
        setWind0(0.162346d);
    	setWind1(0.559800d);
    }
}