
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP55;

import GeneralizedHelicopter.*;

public class HPMDP55 extends AbstractProvingMDPHelicopter{

    public HPMDP55(){
	super();
        setWind0(-0.805017d);
    	setWind1(0.138119d);
    }
}