
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP49;

import GeneralizedHelicopter.*;

public class HPMDP49 extends AbstractProvingMDPHelicopter{

    public HPMDP49(){
	super();
        setWind0(0.971504d);
    	setWind1(-0.758884d);
    }
}