
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package org.rlcommunity.environment.generalizedacrobot;

public class GenAcrobotParamData {

    void setParameters(int ParamSet, GeneralizedAcrobot thisEnvironment) {
        switch (ParamSet) {
            case 0:
                double p0[] = {1.0d,0.05d,1.0d,1.0d,0.0d,0.0d,0.0d,0.0d};
                System.out.println("Selected Standard Acrobot");
                thisEnvironment.setCompetition(false);
                thisEnvironment.setRandomStarts(false);
                thisEnvironment.setCompetitionParams( p0 );              
                break;
            case 1:
                double p1[] = {1.200000 , 0.060000 , 0.163610 , 0.846257 , -2.265722 , -0.009009 , -0.967846 , -0.436355 };
                thisEnvironment.setCompetition(true);
                thisEnvironment.setRandomStarts(true);
                thisEnvironment.setCompetitionParams( p1 );              
                break;
            case 2:
                double p2[] = {1.600000 , 0.020000 , 0.661737 , 0.535628 , -1.546012 , -0.394796 , -0.056421 , 0.833551 };
                thisEnvironment.setCompetition(true);
                thisEnvironment.setRandomStarts(true);
                thisEnvironment.setCompetitionParams( p2 );              
                break;
            case 3:
                double p3[] = {1.000000 , 0.010000 , 0.600908 , 0.804883 , 0.623125 , 2.801172 , -0.924550 , 0.211586 };
                thisEnvironment.setCompetition(true);
                thisEnvironment.setRandomStarts(true);
                thisEnvironment.setCompetitionParams( p3 );              
                break;
            case 4:
                double p4[] = {0.900000 , 0.050000 , 0.631432 , 0.318573 , 1.015295 , 1.305185 , 0.170988 , 0.925676 };
                thisEnvironment.setCompetition(true);
                thisEnvironment.setRandomStarts(true);
                thisEnvironment.setCompetitionParams( p4 );              
                break;
            case 5:
                double p5[] = {1.100000 , 0.020000 , 0.190562 , 0.208966 , 2.527627 , -1.172719 , 0.436522 , 0.603585 };
                thisEnvironment.setCompetition(true);
                thisEnvironment.setRandomStarts(true);
                thisEnvironment.setCompetitionParams( p5 );              
                break;
            case 6:
                double p6[] = {1.300000 , 0.020000 , 0.361206 , 0.145923 , -0.738249 , 1.874555 , -0.023996 , -0.951331 };
                thisEnvironment.setCompetition(true);
                thisEnvironment.setRandomStarts(true);
                thisEnvironment.setCompetitionParams( p6 );              
                break;
            case 7:
                double p7[] = {0.800000 , 0.070000 , 0.525813 , 0.336448 , 0.857039 , 0.579500 , 0.691950 , 0.973902 };
                thisEnvironment.setCompetition(true);
                thisEnvironment.setRandomStarts(true);
                thisEnvironment.setCompetitionParams( p7 );              
                break;
            case 8:
                double p8[] = {0.800000 , 0.020000 , 0.520552 , 0.460436 , -0.986111 , -1.788939 , -0.267940 , -0.965995 };
                thisEnvironment.setCompetition(true);
                thisEnvironment.setRandomStarts(true);
                thisEnvironment.setCompetitionParams( p8 );              
                break;
            case 9:
                double p9[] = {1.900000 , 0.060000 , 0.420422 , 0.766846 , 2.517760 , -1.610521 , 0.044233 , 0.825580 };
                thisEnvironment.setCompetition(true);
                thisEnvironment.setRandomStarts(true);
                thisEnvironment.setCompetitionParams( p9 );              
                break;
            case 10:
                double p10[] = {1.500000 , 0.040000 , 0.893863 , 0.379771 , -0.981930 , -2.582930 , 0.882443 , -0.925951 };
                thisEnvironment.setCompetition(true);
                thisEnvironment.setRandomStarts(true);
                thisEnvironment.setCompetitionParams( p10 );              
                break;
            case 11:
                double p11[] = {1.200000 , 0.080000 , 0.211854 , 0.286398 , 0.303091 , 0.182579 , -0.891433 , 0.679021 };
                thisEnvironment.setCompetition(true);
                thisEnvironment.setRandomStarts(true);
                thisEnvironment.setCompetitionParams( p11 );              
                break;
            case 12:
                double p12[] = {1.000000 , 0.040000 , 0.700120 , 0.150035 , 2.349175 , 1.609858 , 0.995082 , 0.232486 };
                thisEnvironment.setCompetition(true);
                thisEnvironment.setRandomStarts(true);
                thisEnvironment.setCompetitionParams( p12 );              
                break;
            case 13:
                double p13[] = {1.300000 , 0.060000 , 0.332642 , 0.886704 , 2.890477 , 1.415632 , -0.486660 , -0.577114 };
                thisEnvironment.setCompetition(true);
                thisEnvironment.setRandomStarts(true);
                thisEnvironment.setCompetitionParams( p13 );              
                break;
            case 14:
                double p14[] = {0.900000 , 0.050000 , 0.904985 , 0.680047 , -0.236145 , 0.549270 , -0.035747 , -0.851118 };
                thisEnvironment.setCompetition(true);
                thisEnvironment.setRandomStarts(true);
                thisEnvironment.setCompetitionParams( p14 );              
                break;
            case 15:
                double p15[] = {1.400000 , 0.070000 , 0.333518 , 0.151845 , 0.229451 , 0.025909 , 0.708164 , -0.046406 };
                thisEnvironment.setCompetition(true);
                thisEnvironment.setRandomStarts(true);
                thisEnvironment.setCompetitionParams( p15 );              
                break;
            case 16:
                double p16[] = {1.900000 , 0.080000 , 0.162999 , 0.778527 , -1.682643 , 0.888908 , -0.823970 , 0.374998 };
                thisEnvironment.setCompetition(true);
                thisEnvironment.setRandomStarts(true);
                thisEnvironment.setCompetitionParams( p16 );              
                break;
            case 17:
                double p17[] = {1.100000 , 0.040000 , 0.474418 , 0.981213 , -1.310056 , 1.224837 , 0.630822 , 0.765315 };
                thisEnvironment.setCompetition(true);
                thisEnvironment.setRandomStarts(true);
                thisEnvironment.setCompetitionParams( p17 );              
                break;
            case 18:
                double p18[] = {1.000000 , 0.040000 , 0.822722 , 0.474625 , -2.522964 , 2.858416 , -0.270788 , 0.739492 };
                thisEnvironment.setCompetition(true);
                thisEnvironment.setRandomStarts(true);
                thisEnvironment.setCompetitionParams( p18 );              
                break;
            case 19:
                double p19[] = {1.400000 , 0.030000 , 0.216062 , 0.819236 , 1.266929 , -2.749128 , -0.313341 , 0.635999 };
                thisEnvironment.setCompetition(true);
                thisEnvironment.setRandomStarts(true);
                thisEnvironment.setCompetitionParams( p19 );              
                break;
            case 20:
                double p20[] = {1.300000 , 0.060000 , 0.752673 , 0.327384 , 1.779273 , -0.497272 , 0.988761 , 0.900691 };
                thisEnvironment.setCompetition(true);
                thisEnvironment.setRandomStarts(true);
                thisEnvironment.setCompetitionParams( p20 );              
                break;
            case 21:
                double p21[] = {1.300000 , 0.040000 , 0.217836 , 0.635105 , -2.176537 , -1.700412 , -0.012820 , -0.052300 };
                thisEnvironment.setCompetition(true);
                thisEnvironment.setRandomStarts(true);
                thisEnvironment.setCompetitionParams( p21 );              
                break;
            case 22:
                double p22[] = {1.700000 , 0.080000 , 0.298413 , 0.943129 , 1.780582 , -2.736006 , -0.935202 , -0.687176 };
                thisEnvironment.setCompetition(true);
                thisEnvironment.setRandomStarts(true);
                thisEnvironment.setCompetitionParams( p22 );              
                break;
            case 23:
                double p23[] = {1.600000 , 0.080000 , 0.750585 , 0.872506 , -1.073225 , -1.578016 , 0.997141 , -0.975866 };
                thisEnvironment.setCompetition(true);
                thisEnvironment.setRandomStarts(true);
                thisEnvironment.setCompetitionParams( p23 );              
                break;
            case 24:
                double p24[] = {0.800000 , 0.030000 , 0.203361 , 0.629860 , 3.074567 , 0.183082 , -0.903642 , -0.451077 };
                thisEnvironment.setCompetition(true);
                thisEnvironment.setRandomStarts(true);
                thisEnvironment.setCompetitionParams( p24 );              
                break;
            case 25:
                double p25[] = {1.400000 , 0.040000 , 0.370542 , 0.415547 , 2.671673 , 1.885112 , 0.016097 , -0.420992 };
                thisEnvironment.setCompetition(true);
                thisEnvironment.setRandomStarts(true);
                thisEnvironment.setCompetitionParams( p25 );              
                break;
            case 26:
                double p26[] = {1.200000 , 0.080000 , 0.155810 , 0.904794 , -2.054880 , 0.430733 , 0.657062 , 0.553468 };
                thisEnvironment.setCompetition(true);
                thisEnvironment.setRandomStarts(true);
                thisEnvironment.setCompetitionParams( p26 );              
                break;
            case 27:
                double p27[] = {1.300000 , 0.010000 , 0.251358 , 0.402840 , 0.409251 , -0.485135 , 0.361194 , -0.251834 };
                thisEnvironment.setCompetition(true);
                thisEnvironment.setRandomStarts(true);
                thisEnvironment.setCompetitionParams( p27 );              
                break;
            case 28:
                double p28[] = {1.400000 , 0.070000 , 0.993109 , 0.166821 , -1.286500 , -1.666957 , 0.621029 , -0.256244 };
                thisEnvironment.setCompetition(true);
                thisEnvironment.setRandomStarts(true);
                thisEnvironment.setCompetitionParams( p28 );              
                break;
            case 29:
                double p29[] = {1.400000 , 0.040000 , 0.299786 , 0.488784 , 3.072328 , -2.901041 , 0.550881 , 0.659820 };
                thisEnvironment.setCompetition(true);
                thisEnvironment.setRandomStarts(true);
                thisEnvironment.setCompetitionParams( p29 );              
                break;
            case 30:
                double p30[] = {1.100000 , 0.020000 , 0.421829 , 0.264360 , 1.792929 , 1.184201 , -0.265389 , -0.545215 };
                thisEnvironment.setCompetition(true);
                thisEnvironment.setRandomStarts(true);
                thisEnvironment.setCompetitionParams( p30 );              
                break;
            case 31:
                double p31[] = {1.300000 , 0.090000 , 0.326326 , 0.960659 , -0.151320 , 0.463721 , 0.027583 , 0.696858 };
                thisEnvironment.setCompetition(true);
                thisEnvironment.setRandomStarts(true);
                thisEnvironment.setCompetitionParams( p31 );              
                break;
            case 32:
                double p32[] = {1.200000 , 0.030000 , 0.248032 , 0.102579 , -0.315777 , 2.682463 , 0.143249 , -0.071440 };
                thisEnvironment.setCompetition(true);
                thisEnvironment.setRandomStarts(true);
                thisEnvironment.setCompetitionParams( p32 );              
                break;
            case 33:
                double p33[] = {1.500000 , 0.020000 , 0.834154 , 0.680530 , 2.474599 , 0.749422 , 0.572793 , -0.437710 };
                thisEnvironment.setCompetition(true);
                thisEnvironment.setRandomStarts(true);
                thisEnvironment.setCompetitionParams( p33 );              
                break;
            case 34:
                double p34[] = {1.400000 , 0.050000 , 0.175887 , 0.683186 , 3.005225 , 2.145559 , -0.438905 , 0.576245 };
                thisEnvironment.setCompetition(true);
                thisEnvironment.setRandomStarts(true);
                thisEnvironment.setCompetitionParams( p34 );              
                break;
            case 35:
                double p35[] = {0.800000 , 0.090000 , 0.449424 , 0.590993 , 1.212046 , 2.813442 , -0.612288 , 0.704472 };
                thisEnvironment.setCompetition(true);
                thisEnvironment.setRandomStarts(true);
                thisEnvironment.setCompetitionParams( p35 );              
                break;
            case 36:
                double p36[] = {1.400000 , 0.020000 , 0.840373 , 0.319354 , 2.782464 , -1.368619 , 0.704404 , -0.280305 };
                thisEnvironment.setCompetition(true);
                thisEnvironment.setRandomStarts(true);
                thisEnvironment.setCompetitionParams( p36 );              
                break;
            case 37:
                double p37[] = {1.300000 , 0.020000 , 0.809996 , 0.368796 , -3.003228 , 2.326241 , -0.621815 , -0.958068 };
                thisEnvironment.setCompetition(true);
                thisEnvironment.setRandomStarts(true);
                thisEnvironment.setCompetitionParams( p37 );              
                break;
            case 38:
                double p38[] = {1.600000 , 0.080000 , 0.448834 , 0.512356 , -1.617232 , 1.446203 , 0.262928 , 0.931622 };
                thisEnvironment.setCompetition(true);
                thisEnvironment.setRandomStarts(true);
                thisEnvironment.setCompetitionParams( p38 );              
                break;
            case 39:
                double p39[] = {0.800000 , 0.080000 , 0.697010 , 0.610530 , -1.897165 , 0.692258 , -0.740648 , -0.596463 };
                thisEnvironment.setCompetition(true);
                thisEnvironment.setRandomStarts(true);
                thisEnvironment.setCompetitionParams( p39 );              
                break;
            default:
                System.err.println("Invalid Parameter Set Requested ("+ParamSet+") : using Param Set 0");
                setParameters(0, thisEnvironment);
        }
    }
}