
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP26;

import GeneralizedHelicopter.*;

public class HPMDP26 extends AbstractProvingMDPHelicopter{

    public HPMDP26(){
	super();
        setWind0(0.305824d);
    	setWind1(0.600994d);
    }
}