
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP50;

import GeneralizedHelicopter.*;

public class HPMDP50 extends AbstractProvingMDPHelicopter{

    public HPMDP50(){
	super();
        setWind0(0.739280d);
    	setWind1(-0.376526d);
    }
}