
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP73;

import GeneralizedHelicopter.*;

public class HPMDP73 extends AbstractProvingMDPHelicopter{

    public HPMDP73(){
	super();
        setWind0(-0.487198d);
    	setWind1(0.343453d);
    }
}