
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP13;

import GeneralizedHelicopter.*;

public class HPMDP13 extends AbstractProvingMDPHelicopter{

    public HPMDP13(){
	super();
        setWind0(-0.078475d);
    	setWind1(-0.751539d);
    }
}