
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP25;

import GeneralizedHelicopter.*;

public class HPMDP25 extends AbstractProvingMDPHelicopter{

    public HPMDP25(){
	super();
        setWind0(-0.536978d);
    	setWind1(-0.733914d);
    }
}