
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP87;

import GeneralizedHelicopter.*;

public class HPMDP87 extends AbstractProvingMDPHelicopter{

    public HPMDP87(){
	super();
        setWind0(-0.658360d);
    	setWind1(0.025400d);
    }
}