
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP7;

import GeneralizedHelicopter.*;

public class HPMDP7 extends AbstractProvingMDPHelicopter{

    public HPMDP7(){
	super();
        setWind0(0.360428d);
    	setWind1(0.471989d);
    }
}