
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP16;

import GeneralizedHelicopter.*;

public class HPMDP16 extends AbstractProvingMDPHelicopter{

    public HPMDP16(){
	super();
        setWind0(0.940042d);
    	setWind1(-0.847786d);
    }
}