
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP39;

import GeneralizedHelicopter.*;

public class HPMDP39 extends AbstractProvingMDPHelicopter{

    public HPMDP39(){
	super();
        setWind0(0.457820d);
    	setWind1(0.479161d);
    }
}