
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP92;

import GeneralizedHelicopter.*;

public class HPMDP92 extends AbstractProvingMDPHelicopter{

    public HPMDP92(){
	super();
        setWind0(0.174900d);
    	setWind1(0.921453d);
    }
}