
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP78;

import GeneralizedHelicopter.*;

public class HPMDP78 extends AbstractProvingMDPHelicopter{

    public HPMDP78(){
	super();
        setWind0(-0.250535d);
    	setWind1(0.425561d);
    }
}