
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP76;

import GeneralizedHelicopter.*;

public class HPMDP76 extends AbstractProvingMDPHelicopter{

    public HPMDP76(){
	super();
        setWind0(0.004920d);
    	setWind1(-0.571473d);
    }
}