
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP85;

import GeneralizedHelicopter.*;

public class HPMDP85 extends AbstractProvingMDPHelicopter{

    public HPMDP85(){
	super();
        setWind0(0.818338d);
    	setWind1(0.276639d);
    }
}