
/*
 * This code was auto-generated by the parameter script, GenParams.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.generalized;

public class GenHeliParamData {

    void setParameters(int paramSet, GeneralizedHelicopter thisEnvironment) {
        switch (paramSet) {
            case 0:
                thisEnvironment.setWindWaveNS(0.693851d, 0.115374d, 0.669592d, 0.588185d);
                thisEnvironment.setWindWaveEW(0.853936d, 0.252569d, 0.757596d, 0.367433d);
                break;
            case 1:
                thisEnvironment.setWindWaveNS(0.720038d, 0.635304d, 0.044392d, 0.648565d);
                thisEnvironment.setWindWaveEW(0.132414d, 0.259877d, 0.086958d, 0.813711d);
                break;
            case 2:
                thisEnvironment.setWindWaveNS(0.724593d, 0.666699d, 0.311691d, 0.786064d);
                thisEnvironment.setWindWaveEW(0.600669d, 0.021126d, 0.236896d, 0.562895d);
                break;
            case 3:
                thisEnvironment.setWindWaveNS(0.607132d, 0.442880d, 0.360980d, 0.167207d);
                thisEnvironment.setWindWaveEW(0.081301d, 0.742238d, 0.002850d, 0.550981d);
                break;
            case 4:
                thisEnvironment.setWindWaveNS(0.949278d, 0.276789d, 0.115042d, 0.270776d);
                thisEnvironment.setWindWaveEW(0.268197d, 0.861445d, 0.942433d, 0.971455d);
                break;
            case 5:
                thisEnvironment.setWindWaveNS(0.550625d, 0.867898d, 0.916801d, 0.643898d);
                thisEnvironment.setWindWaveEW(0.211139d, 0.425095d, 0.758741d, 0.897585d);
                break;
            case 6:
                thisEnvironment.setWindWaveNS(0.116730d, 0.373797d, 0.113577d, 0.766653d);
                thisEnvironment.setWindWaveEW(0.428122d, 0.021471d, 0.995174d, 0.281151d);
                break;
            case 7:
                thisEnvironment.setWindWaveNS(0.680743d, 0.024624d, 0.224401d, 0.606206d);
                thisEnvironment.setWindWaveEW(0.739881d, 0.397792d, 0.043179d, 0.897237d);
                break;
            case 8:
                thisEnvironment.setWindWaveNS(0.397997d, 0.791233d, 0.736065d, 0.738457d);
                thisEnvironment.setWindWaveEW(0.989597d, 0.169351d, 0.532904d, 0.149639d);
                break;
            case 9:
                thisEnvironment.setWindWaveNS(0.187150d, 0.631497d, 0.268372d, 0.896376d);
                thisEnvironment.setWindWaveEW(0.190854d, 0.726746d, 0.766254d, 0.929489d);
                break;
            default:
                System.err.println("Invalid Parameter Set Requested ("+paramSet+") : using Param Set 0");
                setParameters(0, thisEnvironment);
        }
    }
}
