
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP84;

import GeneralizedHelicopter.*;

public class HPMDP84 extends AbstractProvingMDPHelicopter{

    public HPMDP84(){
	super();
        setWind0(0.464451d);
    	setWind1(-0.407500d);
    }
}