
//package org.rlcommunity.environment.testing;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotTesting23 extends AbstractProvingMDPAcrobot {

    public AcrobotTesting23() {
        super();
        double p[] = {1.100000 , 0.040000 , 0.624171 , 0.283832 , -1.230427 , 2.576999 , 0.059162 , 0.091036 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        