
//package org.rlcommunity.environment.testing;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotTesting7 extends AbstractProvingMDPAcrobot {

    public AcrobotTesting7() {
        super();
        double p[] = {1.600000 , 0.070000 , 0.956082 , 0.793717 , 1.004989 , -2.233787 , 0.534322 , -0.396917 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        