
//package org.rlcommunity.environment.testing;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotTesting10 extends AbstractProvingMDPAcrobot {

    public AcrobotTesting10() {
        super();
        double p[] = {1.500000 , 0.070000 , 0.356025 , 0.592964 , -0.294653 , 2.065946 , -0.522020 , -0.180254 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        