
//package org.rlcommunity.environment.testing;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotTesting18 extends AbstractProvingMDPAcrobot {

    public AcrobotTesting18() {
        super();
        double p[] = {1.600000 , 0.050000 , 0.307195 , 0.907706 , -1.406663 , 1.343293 , -0.546982 , 0.780484 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        