
//package org.rlcommunity.environment.testing;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotTesting3 extends AbstractProvingMDPAcrobot {

    public AcrobotTesting3() {
        super();
        double p[] = {1.700000 , 0.080000 , 0.679400 , 0.914022 , 2.763571 , 0.166094 , -0.104768 , 0.052994 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        