
//package org.rlcommunity.environment.testing;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotTesting19 extends AbstractProvingMDPAcrobot {

    public AcrobotTesting19() {
        super();
        double p[] = {1.200000 , 0.050000 , 0.126722 , 0.908890 , -2.749638 , 2.928461 , 0.762787 , 0.905191 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        