
//package org.rlcommunity.environment.testing;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotTesting9 extends AbstractProvingMDPAcrobot {

    public AcrobotTesting9() {
        super();
        double p[] = {1.400000 , 0.070000 , 0.137971 , 0.212848 , -1.081517 , 1.763377 , -0.462479 , 0.107106 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        