
//package org.rlcommunity.environment.testing;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotTesting1 extends AbstractProvingMDPAcrobot {

    public AcrobotTesting1() {
        super();
        double p[] = {1.400000 , 0.010000 , 0.963184 , 0.105955 , -2.677722 , -1.996213 , -0.751817 , -0.277247 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        