
//package org.rlcommunity.environment.testing;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotTesting14 extends AbstractProvingMDPAcrobot {

    public AcrobotTesting14() {
        super();
        double p[] = {1.300000 , 0.070000 , 0.119010 , 0.600241 , -3.081781 , -0.613438 , -0.520372 , 0.023367 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        