
//package org.rlcommunity.environment.testing;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotTesting13 extends AbstractProvingMDPAcrobot {

    public AcrobotTesting13() {
        super();
        double p[] = {1.300000 , 0.070000 , 0.360536 , 0.751396 , 3.065241 , -0.590757 , 0.990597 , -0.954815 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        