
//package org.rlcommunity.environment.testing;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotTesting21 extends AbstractProvingMDPAcrobot {

    public AcrobotTesting21() {
        super();
        double p[] = {1.300000 , 0.030000 , 0.460342 , 0.209604 , 1.037568 , -1.723846 , 0.137727 , -0.323132 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        