
//package org.rlcommunity.environment.testing;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotTesting5 extends AbstractProvingMDPAcrobot {

    public AcrobotTesting5() {
        super();
        double p[] = {1.200000 , 0.010000 , 0.786039 , 0.348280 , 1.602732 , -1.258113 , -0.343981 , -0.690133 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        