
//package org.rlcommunity.environment.testing;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotTesting17 extends AbstractProvingMDPAcrobot {

    public AcrobotTesting17() {
        super();
        double p[] = {1.100000 , 0.010000 , 0.522094 , 0.334231 , 0.135673 , 1.078689 , -0.432137 , -0.485864 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        