
//package org.rlcommunity.environment.testing;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotTesting22 extends AbstractProvingMDPAcrobot {

    public AcrobotTesting22() {
        super();
        double p[] = {1.500000 , 0.020000 , 0.629044 , 0.380639 , 0.295292 , -3.134637 , -0.679491 , -0.277286 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        