
//package org.rlcommunity.environment.testing;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotTesting4 extends AbstractProvingMDPAcrobot {

    public AcrobotTesting4() {
        super();
        double p[] = {1.800000 , 0.060000 , 0.653681 , 0.437151 , -1.732781 , 0.623127 , -0.793578 , 0.880551 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        