
//package org.rlcommunity.environment.testing;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotTesting2 extends AbstractProvingMDPAcrobot {

    public AcrobotTesting2() {
        super();
        double p[] = {1.500000 , 0.050000 , 0.673516 , 0.595168 , -0.579897 , 3.048469 , -0.187269 , -0.431788 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        