
//package org.rlcommunity.environment.testing;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotTesting20 extends AbstractProvingMDPAcrobot {

    public AcrobotTesting20() {
        super();
        double p[] = {1.500000 , 0.070000 , 0.486709 , 0.545403 , -1.109908 , 0.798389 , 0.501597 , 0.003265 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        