
//package org.rlcommunity.environment.testing;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotTesting11 extends AbstractProvingMDPAcrobot {

    public AcrobotTesting11() {
        super();
        double p[] = {1.400000 , 0.080000 , 0.717187 , 0.463987 , -1.342618 , 2.895428 , 0.163724 , 0.367770 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        