
//package org.rlcommunity.environment.testing;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotTesting25 extends AbstractProvingMDPAcrobot {

    public AcrobotTesting25() {
        super();
        double p[] = {0.800000 , 0.090000 , 0.987607 , 0.392548 , -1.747606 , 3.019181 , 0.034176 , -0.346126 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        