
//package org.rlcommunity.environment.testing;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotTesting15 extends AbstractProvingMDPAcrobot {

    public AcrobotTesting15() {
        super();
        double p[] = {1.800000 , 0.070000 , 0.208989 , 0.866448 , 2.071010 , 2.502408 , 0.141763 , -0.815717 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        