
//package org.rlcommunity.environment.testing;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotTesting24 extends AbstractProvingMDPAcrobot {

    public AcrobotTesting24() {
        super();
        double p[] = {1.900000 , 0.070000 , 0.120340 , 0.351044 , 2.553431 , 1.436583 , -0.047061 , -0.487860 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        