
//package org.rlcommunity.environment.testing;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotTesting6 extends AbstractProvingMDPAcrobot {

    public AcrobotTesting6() {
        super();
        double p[] = {1.000000 , 0.030000 , 1.000802 , 0.928185 , 0.145477 , -1.203246 , -0.246792 , 0.300883 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        