
//package org.rlcommunity.environment.testing;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotTesting8 extends AbstractProvingMDPAcrobot {

    public AcrobotTesting8() {
        super();
        double p[] = {1.000000 , 0.030000 , 0.621067 , 0.103183 , -1.668581 , 2.985400 , 0.103087 , -0.174145 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        