
//package org.rlcommunity.environment.testing;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotTesting12 extends AbstractProvingMDPAcrobot {

    public AcrobotTesting12() {
        super();
        double p[] = {1.800000 , 0.020000 , 0.722519 , 0.471521 , 0.909011 , 2.859252 , 0.636454 , -0.424453 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        