
//package org.rlcommunity.environment.testing;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotTesting16 extends AbstractProvingMDPAcrobot {

    public AcrobotTesting16() {
        super();
        double p[] = {1.400000 , 0.040000 , 0.726246 , 1.004856 , 2.370492 , -0.458539 , 0.503770 , 0.727624 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        