
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP32;

import GeneralizedHelicopter.*;

public class HPMDP32 extends AbstractProvingMDPHelicopter{

    public HPMDP32(){
	super();
        setWind0(0.077578d);
    	setWind1(-0.964760d);
    }
}