
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP27;

import GeneralizedHelicopter.*;

public class HPMDP27 extends AbstractProvingMDPHelicopter{

    public HPMDP27(){
	super();
        setWind0(0.767343d);
    	setWind1(0.682454d);
    }
}