
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP2;

import GeneralizedHelicopter.*;

public class HPMDP2 extends AbstractProvingMDPHelicopter{

    public HPMDP2(){
	super();
        setWind0(-0.736982d);
    	setWind1(-0.449372d);
    }
}