
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP48;

import GeneralizedHelicopter.*;

public class HPMDP48 extends AbstractProvingMDPHelicopter{

    public HPMDP48(){
	super();
        setWind0(-0.248307d);
    	setWind1(0.007722d);
    }
}