
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP43;

import GeneralizedHelicopter.*;

public class HPMDP43 extends AbstractProvingMDPHelicopter{

    public HPMDP43(){
	super();
        setWind0(-0.243714d);
    	setWind1(0.138319d);
    }
}