
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP1;

import GeneralizedHelicopter.*;

public class HPMDP1 extends AbstractProvingMDPHelicopter{

    public HPMDP1(){
	super();
        setWind0(-0.620649d);
    	setWind1(0.528575d);
    }
}