
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP5;

import GeneralizedHelicopter.*;

public class HPMDP5 extends AbstractProvingMDPHelicopter{

    public HPMDP5(){
	super();
        setWind0(-0.486639d);
    	setWind1(0.123578d);
    }
}