
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP30;

import GeneralizedHelicopter.*;

public class HPMDP30 extends AbstractProvingMDPHelicopter{

    public HPMDP30(){
	super();
        setWind0(0.800311d);
    	setWind1(-0.274053d);
    }
}