
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP22;

import GeneralizedHelicopter.*;

public class HPMDP22 extends AbstractProvingMDPHelicopter{

    public HPMDP22(){
	super();
        setWind0(0.929061d);
    	setWind1(0.884426d);
    }
}