
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP21;

import GeneralizedHelicopter.*;

public class HPMDP21 extends AbstractProvingMDPHelicopter{

    public HPMDP21(){
	super();
        setWind0(-0.436883d);
    	setWind1(-0.572197d);
    }
}