
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP69;

import GeneralizedHelicopter.*;

public class HPMDP69 extends AbstractProvingMDPHelicopter{

    public HPMDP69(){
	super();
        setWind0(-0.788696d);
    	setWind1(0.256571d);
    }
}