
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP97;

import GeneralizedHelicopter.*;

public class HPMDP97 extends AbstractProvingMDPHelicopter{

    public HPMDP97(){
	super();
        setWind0(-0.062166d);
    	setWind1(-0.597598d);
    }
}