
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP35;

import GeneralizedHelicopter.*;

public class HPMDP35 extends AbstractProvingMDPHelicopter{

    public HPMDP35(){
	super();
        setWind0(-0.706835d);
    	setWind1(-0.432618d);
    }
}