
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP28;

import GeneralizedHelicopter.*;

public class HPMDP28 extends AbstractProvingMDPHelicopter{

    public HPMDP28(){
	super();
        setWind0(-0.770945d);
    	setWind1(0.586594d);
    }
}