
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP18;

import GeneralizedHelicopter.*;

public class HPMDP18 extends AbstractProvingMDPHelicopter{

    public HPMDP18(){
	super();
        setWind0(-0.055490d);
    	setWind1(-0.099921d);
    }
}