
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package GeneralizedHelicopter;

public class GenHeliParamData {

    void setParameters(int ParamSet, GeneralizedHelicopter thisEnvironment) {
        switch (ParamSet) {
            case 0:
                thisEnvironment.setWind0(-0.982730d);
                thisEnvironment.setWind1(0.631781d);
                break;
            case 1:
                thisEnvironment.setWind0(-0.045686d);
                thisEnvironment.setWind1(0.579628d);
                break;
            case 2:
                thisEnvironment.setWind0(-0.102530d);
                thisEnvironment.setWind1(-0.270641d);
                break;
            case 3:
                thisEnvironment.setWind0(0.762356d);
                thisEnvironment.setWind1(0.283768d);
                break;
            case 4:
                thisEnvironment.setWind0(-0.489788d);
                thisEnvironment.setWind1(0.569548d);
                break;
            case 5:
                thisEnvironment.setWind0(0.999573d);
                thisEnvironment.setWind1(0.149759d);
                break;
            case 6:
                thisEnvironment.setWind0(0.887261d);
                thisEnvironment.setWind1(0.382718d);
                break;
            case 7:
                thisEnvironment.setWind0(-0.150035d);
                thisEnvironment.setWind1(-0.841268d);
                break;
            case 8:
                thisEnvironment.setWind0(0.812929d);
                thisEnvironment.setWind1(0.329428d);
                break;
            case 9:
                thisEnvironment.setWind0(-0.431899d);
                thisEnvironment.setWind1(-0.645667d);
                break;
            default:
                System.err.println("Invalid Parameter Set Requested ("+ParamSet+") : using Param Set 0");
                setParameters(0, thisEnvironment);
        }
    }
}