
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP19;

import GeneralizedHelicopter.*;

public class HPMDP19 extends AbstractProvingMDPHelicopter{

    public HPMDP19(){
	super();
        setWind0(0.790156d);
    	setWind1(-0.855291d);
    }
}