
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP89;

import GeneralizedHelicopter.*;

public class HPMDP89 extends AbstractProvingMDPHelicopter{

    public HPMDP89(){
	super();
        setWind0(0.184435d);
    	setWind1(0.975881d);
    }
}