
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP6;

import GeneralizedHelicopter.*;

public class HPMDP6 extends AbstractProvingMDPHelicopter{

    public HPMDP6(){
	super();
        setWind0(-0.260893d);
    	setWind1(0.084034d);
    }
}