
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP38;

import GeneralizedHelicopter.*;

public class HPMDP38 extends AbstractProvingMDPHelicopter{

    public HPMDP38(){
	super();
        setWind0(-0.714204d);
    	setWind1(0.414413d);
    }
}