
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP3;

import GeneralizedHelicopter.*;

public class HPMDP3 extends AbstractProvingMDPHelicopter{

    public HPMDP3(){
	super();
        setWind0(-0.075114d);
    	setWind1(0.312063d);
    }
}