
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP66;

import GeneralizedHelicopter.*;

public class HPMDP66 extends AbstractProvingMDPHelicopter{

    public HPMDP66(){
	super();
        setWind0(0.111974d);
    	setWind1(0.139250d);
    }
}