import GenParamSamples

# p.addDoubleParam("scaleP",1.0d);//should be between 0 and 1.0, probably not too close to 0
#  p.addDoubleParam("scaleV",1.0d);//should be between 0 and 1.0, probably not too close to 0
# 
#  
# 
#  p.addDoubleParam("pOffset",0.0d); //should be between -1.0 and 1.0, remember to adjust task spec
#  p.addDoubleParam("vOffset",0.0d); //should be between -1.0 and 1.0, remember to adjust task spec
# 
# 
#  p.addDoubleParam("pNoiseDivider",20.0d); //should be between 5.0 and 20.0
#  p.addDoubleParam("vNoiseDivider",20.0d); //should be between 5.0 and 20.0
# 
#  p.addDoubleParam("AccelBiasMean",1.0d); //should be between .8 and whatever larger, say 2.0
# 

method1 = "setScaleP"
method2 = "setScaleV"
method3 = "setPOffset"
method4 = "setVOffset"
method5 = "setPNoiseDivider"
method6 = "setVNoiseDivider"
method7 = "setAccelBiasMean"

f = open('./src/GeneralizedMountainCar/GenMCParamData.java','w')

f.write("""
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package GeneralizedMountainCar;

public class GenMCParamData {

    void setParameters(int ParamSet, GeneralizedMountainCar thisEnvironment) {
        switch (ParamSet) {""")
for i in range(35):
	f.write("""
            case %d:
                thisEnvironment.%s(%fd);
                thisEnvironment.%s(%fd);
                thisEnvironment.%s(%fd);
                thisEnvironment.%s(%fd);
                thisEnvironment.%s(%fd);
                thisEnvironment.%s(%fd);
                thisEnvironment.%s(%fd);
                break;""" % (i, method1, GenParamSamples.sampleP1(i), method2, GenParamSamples.sampleP2(i),method3, GenParamSamples.sampleP3(i),method4, GenParamSamples.sampleP4(i),method5, GenParamSamples.sampleP5(i),method6, GenParamSamples.sampleP6(i),method7, GenParamSamples.sampleP7(i)))

f.write("""
            default:
                System.err.println("Invalid Parameter Set Requested ("+ParamSet+") : using Param Set 0");
                setParameters(0, thisEnvironment);
        }
    }
}""")
f.close()