
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP88;

import GeneralizedHelicopter.*;

public class HPMDP88 extends AbstractProvingMDPHelicopter{

    public HPMDP88(){
	super();
        setWind0(-0.102925d);
    	setWind1(0.478231d);
    }
}