
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP80;

import GeneralizedHelicopter.*;

public class HPMDP80 extends AbstractProvingMDPHelicopter{

    public HPMDP80(){
	super();
        setWind0(0.051023d);
    	setWind1(0.572587d);
    }
}