
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP95;

import GeneralizedHelicopter.*;

public class HPMDP95 extends AbstractProvingMDPHelicopter{

    public HPMDP95(){
	super();
        setWind0(-0.026824d);
    	setWind1(0.350263d);
    }
}