
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP53;

import GeneralizedHelicopter.*;

public class HPMDP53 extends AbstractProvingMDPHelicopter{

    public HPMDP53(){
	super();
        setWind0(-0.041371d);
    	setWind1(0.089830d);
    }
}