
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP83;

import GeneralizedHelicopter.*;

public class HPMDP83 extends AbstractProvingMDPHelicopter{

    public HPMDP83(){
	super();
        setWind0(-0.139520d);
    	setWind1(-0.444840d);
    }
}