
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP14;

import GeneralizedHelicopter.*;

public class HPMDP14 extends AbstractProvingMDPHelicopter{

    public HPMDP14(){
	super();
        setWind0(-0.280772d);
    	setWind1(-0.855634d);
    }
}