
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP24;

import GeneralizedHelicopter.*;

public class HPMDP24 extends AbstractProvingMDPHelicopter{

    public HPMDP24(){
	super();
        setWind0(-0.592990d);
    	setWind1(-0.719097d);
    }
}