
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP62;

import GeneralizedHelicopter.*;

public class HPMDP62 extends AbstractProvingMDPHelicopter{

    public HPMDP62(){
	super();
        setWind0(0.852257d);
    	setWind1(0.621657d);
    }
}