/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class environmentShell_JNIEnvironment */

#ifndef _Included_environmentShell_JNIEnvironment
#define _Included_environmentShell_JNIEnvironment
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     environmentShell_JNIEnvironment
 * Method:    JNIloadEnvironment
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_environmentShell_JNIEnvironment_JNIloadEnvironment
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     environmentShell_JNIEnvironment
 * Method:    JNIenvinit
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_environmentShell_JNIEnvironment_JNIenvinit
  (JNIEnv *, jobject);

/*
 * Class:     environmentShell_JNIEnvironment
 * Method:    JNIenvstart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_environmentShell_JNIEnvironment_JNIenvstart
  (JNIEnv *, jobject);

/*
 * Class:     environmentShell_JNIEnvironment
 * Method:    JNIenvstep
 * Signature: (II[I[D)V
 */
JNIEXPORT void JNICALL Java_environmentShell_JNIEnvironment_JNIenvstep
  (JNIEnv *, jobject, jint, jint, jintArray, jdoubleArray);

/*
 * Class:     environmentShell_JNIEnvironment
 * Method:    JNIenvcleanup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_environmentShell_JNIEnvironment_JNIenvcleanup
  (JNIEnv *, jobject);

/*
 * Class:     environmentShell_JNIEnvironment
 * Method:    JNIenvsetrandomseed
 * Signature: (ID[I[D)V
 */
JNIEXPORT void JNICALL Java_environmentShell_JNIEnvironment_JNIenvsetrandomseed
  (JNIEnv *, jobject, jint, jdouble, jintArray, jdoubleArray);

/*
 * Class:     environmentShell_JNIEnvironment
 * Method:    JNIgetrandomseed
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_environmentShell_JNIEnvironment_JNIgetrandomseed
  (JNIEnv *, jobject);

/*
 * Class:     environmentShell_JNIEnvironment
 * Method:    JNIenvmessage
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_environmentShell_JNIEnvironment_JNIenvmessage
  (JNIEnv *, jobject, jstring);

/*
 * Class:     environmentShell_JNIEnvironment
 * Method:    JNIgetInt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_environmentShell_JNIEnvironment_JNIgetInt
  (JNIEnv *, jobject);

/*
 * Class:     environmentShell_JNIEnvironment
 * Method:    JNIgetIntArray
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_environmentShell_JNIEnvironment_JNIgetIntArray
  (JNIEnv *, jobject);

/*
 * Class:     environmentShell_JNIEnvironment
 * Method:    JNIgetDouble
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_environmentShell_JNIEnvironment_JNIgetDouble
  (JNIEnv *, jobject);

/*
 * Class:     environmentShell_JNIEnvironment
 * Method:    JNIgetDoubleArray
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_environmentShell_JNIEnvironment_JNIgetDoubleArray
  (JNIEnv *, jobject);

/*
 * Class:     environmentShell_JNIEnvironment
 * Method:    JNIgetReward
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_environmentShell_JNIEnvironment_JNIgetReward
  (JNIEnv *, jobject);

/*
 * Class:     environmentShell_JNIEnvironment
 * Method:    JNIgetTerminal
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_environmentShell_JNIEnvironment_JNIgetTerminal
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
