#!/usr/bin/python

#------------------------------------------------------------------------------
# This script will create 'howManyMDPs' different MDPs and add them to the
# specified directory.  Change the variables mdpType to either "testing" or
# "proving" depending on which phase of the competition you want to create MDPs
# for.
#------------------------------------------------------------------------------

import GenParamSamples
import os
from string import capwords

#-------------------------------
# Change these as you see fit!
#-------------------------------
howManyMDPs = 100
#mdpType  = 'proving'
mdpType  = 'testing'

classNamePrefix = "Helicopter" + capwords(mdpType)
method1 = "setWindWaveNS"
method2 = "setWindWaveEW"

if not os.path.isdir('./src/org/rlcommunity/environment/helicopter/' + mdpType):
    print 'Directory ./src/org/rlcommunity/environment/helicopter/' + mdpType
    print '    does not exist.  Creating...'
    os.mkdir('./src/org/rlcommunity/environment/helicopter/' + mdpType)

for i in range(howManyMDPs):
	f = open('./src/org/rlcommunity/environment/helicopter/%s/%s%d.java'% (mdpType, classNamePrefix, i),'w')

	f.write("""
/*
 * This code was auto-generated by the script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.%s;

public class %s%d extends Abstract%sMDPHelicopter {

    public %s%d(){
	super();
        %s(%fd, %fd, %fd, %fd);
    	%s(%fd, %fd, %fd, %fd);
    }
}"""  % (mdpType,
         classNamePrefix,i, capwords(mdpType),
         classNamePrefix,i,
         method1,
            GenParamSamples.sampleP1(i),
            GenParamSamples.sampleP1(i),
            GenParamSamples.sampleP1(i),
            GenParamSamples.sampleP1(i),
         method2,
            GenParamSamples.sampleP2(i),
            GenParamSamples.sampleP2(i),
            GenParamSamples.sampleP2(i),
            GenParamSamples.sampleP2(i),
    ))
	f.close()

print howManyMDPs, 'MDPs created in ./src/org/rlcommunity/environment/helicopter/'+mdpType
