
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP63;

import GeneralizedHelicopter.*;

public class HPMDP63 extends AbstractProvingMDPHelicopter{

    public HPMDP63(){
	super();
        setWind0(-0.059442d);
    	setWind1(0.509190d);
    }
}