import GenParamSamples

method1 = "setWidth"
method2 = "setHeight"
method3 = "setRewardExponent"
method4 = "setPieceWeights"

paramf = open('params1.txt','r')
slist = paramf.readlines()
datalist = [s.split() for s in slist]
numberlist = [map(float,l) for l in datalist]
paramf.close()
slist

f = open('./src/org/rlcommunity/environments/competition2009/GeneralizedTetris/GenTetrisParamData.java','w')

f.write("""
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package org.rlcommunity.environments.competition2009.GeneralizedTetris;

import org.rlcommunity.environments.competition2009.Tetris.GameState;
import org.rlcommunity.environments.competition2009.Tetris.TetrlaisPiece;
import java.util.Vector;

public class GenTetrisParamData {

    GameState setParameters(int ParamSet) {
		int width=0;
		int height=0;
		double []pieceWeights=null;
		double rewardExponent=1.0d;
		double evilness = 0.5;
		int evilAgentType = 0;
		double benchmarkScore = 0.0;
		
		Vector<TetrlaisPiece> possibleBlocks=new Vector<TetrlaisPiece>();
        possibleBlocks.add(TetrlaisPiece.makeLine());
		possibleBlocks.add(TetrlaisPiece.makeSquare());
        possibleBlocks.add(TetrlaisPiece.makeTri());
		possibleBlocks.add(TetrlaisPiece.makeSShape());
		possibleBlocks.add(TetrlaisPiece.makeZShape());
		possibleBlocks.add(TetrlaisPiece.makeLShape());
		possibleBlocks.add(TetrlaisPiece.makeJShape());
 	
        switch (ParamSet) {""")
for i in range(20):
	width=numberlist[i][0]
	height=numberlist[i][1]+width
	rewardExponent=numberlist[i][2]
	pieceWeights=numberlist[i][3:10]
	evilness=numberlist[i][10]
	evilAgentType=numberlist[i][11]
	benchmarkScore=numberlist[i][12]
	f.write("""
          case %d:
			width=%d;
			height=%d;
			rewardExponent=%fd;
			evilness = %fd;
			evilAgentType = %d;
			benchmarkScore=%fd;
           """ % (i, width,  height, rewardExponent,evilness,evilAgentType,benchmarkScore))
	f.write("""
			pieceWeights=new double[]{%fd, %fd, %fd, %fd, %fd, %fd, %fd};
			return new GameState(width,height,possibleBlocks,pieceWeights,rewardExponent,evilness,evilAgentType,benchmarkScore);
			""" %(pieceWeights[0],pieceWeights[1],pieceWeights[2],pieceWeights[3],pieceWeights[4],pieceWeights[5],pieceWeights[6]))


f.write("""
            default:
                System.err.println("Invalid Parameter Set Requested ("+ParamSet+") : using Param Set 0");
                return setParameters(0);
        }
    }
}""")
f.close()
print "ready."