
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP81;

import GeneralizedHelicopter.*;

public class HPMDP81 extends AbstractProvingMDPHelicopter{

    public HPMDP81(){
	super();
        setWind0(0.035730d);
    	setWind1(0.754754d);
    }
}