
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP47;

import GeneralizedHelicopter.*;

public class HPMDP47 extends AbstractProvingMDPHelicopter{

    public HPMDP47(){
	super();
        setWind0(0.238221d);
    	setWind1(-0.285205d);
    }
}