
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP8;

import GeneralizedHelicopter.*;

public class HPMDP8 extends AbstractProvingMDPHelicopter{

    public HPMDP8(){
	super();
        setWind0(-0.052433d);
    	setWind1(-0.342526d);
    }
}