
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP61;

import GeneralizedHelicopter.*;

public class HPMDP61 extends AbstractProvingMDPHelicopter{

    public HPMDP61(){
	super();
        setWind0(-0.208537d);
    	setWind1(0.883721d);
    }
}