
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP90;

import GeneralizedHelicopter.*;

public class HPMDP90 extends AbstractProvingMDPHelicopter{

    public HPMDP90(){
	super();
        setWind0(0.078850d);
    	setWind1(0.261982d);
    }
}