
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP9;

import GeneralizedHelicopter.*;

public class HPMDP9 extends AbstractProvingMDPHelicopter{

    public HPMDP9(){
	super();
        setWind0(-0.537700d);
    	setWind1(0.733001d);
    }
}