
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP93;

import GeneralizedHelicopter.*;

public class HPMDP93 extends AbstractProvingMDPHelicopter{
    public static void main(String[] args){
        HPMDP93 theenv = new HPMDP93();
        String theTaskSpecString = theenv.env_init();
        System.out.println(theTaskSpecString);
    }
    
    public HPMDP93(){
	super();
        setWind0(-0.738064d);
    	setWind1(0.244688d);
        
    }
    
}
