
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP23;

import GeneralizedHelicopter.*;

public class HPMDP23 extends AbstractProvingMDPHelicopter{

    public HPMDP23(){
	super();
        setWind0(-0.774169d);
    	setWind1(0.575602d);
    }
}