
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP74;

import GeneralizedHelicopter.*;

public class HPMDP74 extends AbstractProvingMDPHelicopter{

    public HPMDP74(){
	super();
        setWind0(-0.659916d);
    	setWind1(0.472813d);
    }
}