
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP67;

import GeneralizedHelicopter.*;

public class HPMDP67 extends AbstractProvingMDPHelicopter{

    public HPMDP67(){
	super();
        setWind0(0.539741d);
    	setWind1(0.772420d);
    }
}