
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP54;

import GeneralizedHelicopter.*;

public class HPMDP54 extends AbstractProvingMDPHelicopter{

    public HPMDP54(){
	super();
        setWind0(0.720418d);
    	setWind1(0.999560d);
    }
}