
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving36 extends AbstractProvingMDPHelicopter {

    public HelicopterProving36(){
	super();
        setWindWaveNS(0.352599d, 0.283835d, 0.454409d, 0.689989d);
    	setWindWaveEW(0.362393d, 0.508120d, 0.916627d, 0.268486d);
    }
}