
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving48 extends AbstractProvingMDPHelicopter {

    public HelicopterProving48(){
	super();
        setWindWaveNS(0.011053d, 0.393527d, 0.896293d, 0.555289d);
    	setWindWaveEW(0.920622d, 0.282847d, 0.200626d, 0.450165d);
    }
}