
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving44 extends AbstractProvingMDPHelicopter {

    public HelicopterProving44(){
	super();
        setWindWaveNS(0.709547d, 0.574514d, 0.612352d, 0.063355d);
    	setWindWaveEW(0.804855d, 0.596732d, 0.865347d, 0.000469d);
    }
}