
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving5 extends AbstractProvingMDPHelicopter {

    public HelicopterProving5(){
	super();
        setWindWaveNS(0.624597d, 0.697600d, 0.871028d, 0.405344d);
    	setWindWaveEW(0.468597d, 0.250311d, 0.652864d, 0.628849d);
    }
}