
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving13 extends AbstractProvingMDPHelicopter {

    public HelicopterProving13(){
	super();
        setWindWaveNS(0.101898d, 0.563028d, 0.794741d, 0.273322d);
    	setWindWaveEW(0.719549d, 0.529432d, 0.339667d, 0.296787d);
    }
}