
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving35 extends AbstractProvingMDPHelicopter {

    public HelicopterProving35(){
	super();
        setWindWaveNS(0.641549d, 0.687630d, 0.587024d, 0.013892d);
    	setWindWaveEW(0.632733d, 0.869356d, 0.617046d, 0.195976d);
    }
}