
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving20 extends AbstractProvingMDPHelicopter {

    public HelicopterProving20(){
	super();
        setWindWaveNS(0.595118d, 0.336449d, 0.767736d, 0.196086d);
    	setWindWaveEW(0.557403d, 0.328980d, 0.291080d, 0.632119d);
    }
}