
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving85 extends AbstractProvingMDPHelicopter {

    public HelicopterProving85(){
	super();
        setWindWaveNS(0.784258d, 0.458183d, 0.140435d, 0.342090d);
    	setWindWaveEW(0.728861d, 0.816232d, 0.701334d, 0.813366d);
    }
}