
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving49 extends AbstractProvingMDPHelicopter {

    public HelicopterProving49(){
	super();
        setWindWaveNS(0.270555d, 0.443005d, 0.600424d, 0.038415d);
    	setWindWaveEW(0.305748d, 0.618963d, 0.284003d, 0.170750d);
    }
}