
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving89 extends AbstractProvingMDPHelicopter {

    public HelicopterProving89(){
	super();
        setWindWaveNS(0.881574d, 0.110495d, 0.191036d, 0.159245d);
    	setWindWaveEW(0.677000d, 0.522008d, 0.498671d, 0.607663d);
    }
}