
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving70 extends AbstractProvingMDPHelicopter {

    public HelicopterProving70(){
	super();
        setWindWaveNS(0.735440d, 0.115916d, 0.116452d, 0.841078d);
    	setWindWaveEW(0.859088d, 0.976144d, 0.522373d, 0.201415d);
    }
}