
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving74 extends AbstractProvingMDPHelicopter {

    public HelicopterProving74(){
	super();
        setWindWaveNS(0.413881d, 0.907658d, 0.955530d, 0.206293d);
    	setWindWaveEW(0.857118d, 0.411430d, 0.542359d, 0.680316d);
    }
}