
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving40 extends AbstractProvingMDPHelicopter {

    public HelicopterProving40(){
	super();
        setWindWaveNS(0.731998d, 0.468265d, 0.775928d, 0.713007d);
    	setWindWaveEW(0.995356d, 0.402166d, 0.058987d, 0.579574d);
    }
}