
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving17 extends AbstractProvingMDPHelicopter {

    public HelicopterProving17(){
	super();
        setWindWaveNS(0.517454d, 0.805140d, 0.047081d, 0.775081d);
    	setWindWaveEW(0.693360d, 0.968549d, 0.216061d, 0.657173d);
    }
}