
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving58 extends AbstractProvingMDPHelicopter {

    public HelicopterProving58(){
	super();
        setWindWaveNS(0.894408d, 0.316246d, 0.653390d, 0.516612d);
    	setWindWaveEW(0.897730d, 0.529738d, 0.935406d, 0.715269d);
    }
}