
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving8 extends AbstractProvingMDPHelicopter {

    public HelicopterProving8(){
	super();
        setWindWaveNS(0.112199d, 0.799808d, 0.455327d, 0.518058d);
    	setWindWaveEW(0.199498d, 0.092275d, 0.339664d, 0.467736d);
    }
}