
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving21 extends AbstractProvingMDPHelicopter {

    public HelicopterProving21(){
	super();
        setWindWaveNS(0.864085d, 0.291480d, 0.451776d, 0.159212d);
    	setWindWaveEW(0.536067d, 0.749444d, 0.428404d, 0.726189d);
    }
}