
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving78 extends AbstractProvingMDPHelicopter {

    public HelicopterProving78(){
	super();
        setWindWaveNS(0.381756d, 0.806632d, 0.670379d, 0.081798d);
    	setWindWaveEW(0.193580d, 0.735985d, 0.212128d, 0.130066d);
    }
}