
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving64 extends AbstractProvingMDPHelicopter {

    public HelicopterProving64(){
	super();
        setWindWaveNS(0.685482d, 0.815289d, 0.365287d, 0.570618d);
    	setWindWaveEW(0.125632d, 0.909680d, 0.990985d, 0.211535d);
    }
}