
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving1 extends AbstractProvingMDPHelicopter {

    public HelicopterProving1(){
	super();
        setWindWaveNS(0.706394d, 0.814930d, 0.579832d, 0.233063d);
    	setWindWaveEW(0.090333d, 0.215196d, 0.300837d, 0.813321d);
    }
}