
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving61 extends AbstractProvingMDPHelicopter {

    public HelicopterProving61(){
	super();
        setWindWaveNS(0.102276d, 0.504698d, 0.236318d, 0.711102d);
    	setWindWaveEW(0.848885d, 0.492376d, 0.699548d, 0.161968d);
    }
}