
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving96 extends AbstractProvingMDPHelicopter {

    public HelicopterProving96(){
	super();
        setWindWaveNS(0.174877d, 0.086005d, 0.094344d, 0.415190d);
    	setWindWaveEW(0.664205d, 0.861329d, 0.917160d, 0.185534d);
    }
}