
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving57 extends AbstractProvingMDPHelicopter {

    public HelicopterProving57(){
	super();
        setWindWaveNS(0.156949d, 0.189097d, 0.308027d, 0.800201d);
    	setWindWaveEW(0.156747d, 0.675743d, 0.086200d, 0.028059d);
    }
}