
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving52 extends AbstractProvingMDPHelicopter {

    public HelicopterProving52(){
	super();
        setWindWaveNS(0.751560d, 0.533160d, 0.942600d, 0.519543d);
    	setWindWaveEW(0.950414d, 0.551997d, 0.999348d, 0.261806d);
    }
}