
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving56 extends AbstractProvingMDPHelicopter {

    public HelicopterProving56(){
	super();
        setWindWaveNS(0.692283d, 0.713227d, 0.097750d, 0.070464d);
    	setWindWaveEW(0.476109d, 0.821869d, 0.662961d, 0.241294d);
    }
}