
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving16 extends AbstractProvingMDPHelicopter {

    public HelicopterProving16(){
	super();
        setWindWaveNS(0.118185d, 0.268580d, 0.150221d, 0.893457d);
    	setWindWaveEW(0.115747d, 0.114300d, 0.129414d, 0.423328d);
    }
}