
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving12 extends AbstractProvingMDPHelicopter {

    public HelicopterProving12(){
	super();
        setWindWaveNS(0.652097d, 0.256896d, 0.787083d, 0.673398d);
    	setWindWaveEW(0.789485d, 0.710797d, 0.620872d, 0.946003d);
    }
}