
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving63 extends AbstractProvingMDPHelicopter {

    public HelicopterProving63(){
	super();
        setWindWaveNS(0.871865d, 0.599017d, 0.040948d, 0.354539d);
    	setWindWaveEW(0.042250d, 0.529837d, 0.967724d, 0.843488d);
    }
}