
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving6 extends AbstractProvingMDPHelicopter {

    public HelicopterProving6(){
	super();
        setWindWaveNS(0.317971d, 0.846794d, 0.772329d, 0.800478d);
    	setWindWaveEW(0.252027d, 0.636782d, 0.328346d, 0.142292d);
    }
}