
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving91 extends AbstractProvingMDPHelicopter {

    public HelicopterProving91(){
	super();
        setWindWaveNS(0.316954d, 0.476972d, 0.264034d, 0.821751d);
    	setWindWaveEW(0.230768d, 0.234037d, 0.487698d, 0.926928d);
    }
}