
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving23 extends AbstractProvingMDPHelicopter {

    public HelicopterProving23(){
	super();
        setWindWaveNS(0.661550d, 0.698423d, 0.862778d, 0.854455d);
    	setWindWaveEW(0.130212d, 0.874788d, 0.538902d, 0.092286d);
    }
}