
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving27 extends AbstractProvingMDPHelicopter {

    public HelicopterProving27(){
	super();
        setWindWaveNS(0.069762d, 0.625956d, 0.289958d, 0.676681d);
    	setWindWaveEW(0.623518d, 0.968572d, 0.311990d, 0.902872d);
    }
}