
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving19 extends AbstractProvingMDPHelicopter {

    public HelicopterProving19(){
	super();
        setWindWaveNS(0.673764d, 0.746589d, 0.806058d, 0.799348d);
    	setWindWaveEW(0.040477d, 0.794529d, 0.515619d, 0.756951d);
    }
}