
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving7 extends AbstractProvingMDPHelicopter {

    public HelicopterProving7(){
	super();
        setWindWaveNS(0.723722d, 0.086225d, 0.799634d, 0.412055d);
    	setWindWaveEW(0.371678d, 0.756689d, 0.067205d, 0.426579d);
    }
}