
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving55 extends AbstractProvingMDPHelicopter {

    public HelicopterProving55(){
	super();
        setWindWaveNS(0.766417d, 0.696474d, 0.068450d, 0.697241d);
    	setWindWaveEW(0.058203d, 0.497749d, 0.742561d, 0.346368d);
    }
}