
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving4 extends AbstractProvingMDPHelicopter {

    public HelicopterProving4(){
	super();
        setWindWaveNS(0.809113d, 0.315131d, 0.081048d, 0.673089d);
    	setWindWaveEW(0.181486d, 0.377584d, 0.067561d, 0.768417d);
    }
}