
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving51 extends AbstractProvingMDPHelicopter {

    public HelicopterProving51(){
	super();
        setWindWaveNS(0.892251d, 0.179260d, 0.811847d, 0.342797d);
    	setWindWaveEW(0.311062d, 0.454461d, 0.056412d, 0.057772d);
    }
}