
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving18 extends AbstractProvingMDPHelicopter {

    public HelicopterProving18(){
	super();
        setWindWaveNS(0.736310d, 0.865486d, 0.411340d, 0.557394d);
    	setWindWaveEW(0.490616d, 0.917960d, 0.719640d, 0.037897d);
    }
}