
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving0 extends AbstractProvingMDPHelicopter {

    public HelicopterProving0(){
	super();
        setWindWaveNS(0.579304d, 0.392814d, 0.154839d, 0.773059d);
    	setWindWaveEW(0.944671d, 0.139281d, 0.836592d, 0.301931d);
    }
}
