
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving88 extends AbstractProvingMDPHelicopter {

    public HelicopterProving88(){
	super();
        setWindWaveNS(0.716238d, 0.018076d, 0.747026d, 0.670045d);
    	setWindWaveEW(0.405817d, 0.796920d, 0.854671d, 0.659050d);
    }
}