
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving68 extends AbstractProvingMDPHelicopter {

    public HelicopterProving68(){
	super();
        setWindWaveNS(0.912640d, 0.456675d, 0.399582d, 0.096145d);
    	setWindWaveEW(0.469259d, 0.044282d, 0.472916d, 0.424670d);
    }
}