
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving71 extends AbstractProvingMDPHelicopter {

    public HelicopterProving71(){
	super();
        setWindWaveNS(0.804595d, 0.597806d, 0.285513d, 0.363188d);
    	setWindWaveEW(0.973533d, 0.047342d, 0.751551d, 0.295449d);
    }
}