
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving75 extends AbstractProvingMDPHelicopter {

    public HelicopterProving75(){
	super();
        setWindWaveNS(0.055031d, 0.746833d, 0.917588d, 0.259131d);
    	setWindWaveEW(0.633517d, 0.575757d, 0.220252d, 0.399242d);
    }
}