
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving32 extends AbstractProvingMDPHelicopter {

    public HelicopterProving32(){
	super();
        setWindWaveNS(0.605494d, 0.755638d, 0.063280d, 0.087091d);
    	setWindWaveEW(0.030874d, 0.312557d, 0.873855d, 0.009059d);
    }
}