
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving84 extends AbstractProvingMDPHelicopter {

    public HelicopterProving84(){
	super();
        setWindWaveNS(0.048610d, 0.812983d, 0.621190d, 0.051109d);
    	setWindWaveEW(0.696783d, 0.547171d, 0.086789d, 0.321579d);
    }
}