
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving10 extends AbstractProvingMDPHelicopter {

    public HelicopterProving10(){
	super();
        setWindWaveNS(0.778488d, 0.629651d, 0.007701d, 0.218330d);
    	setWindWaveEW(0.000985d, 0.480362d, 0.692846d, 0.827237d);
    }
}