
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving29 extends AbstractProvingMDPHelicopter {

    public HelicopterProving29(){
	super();
        setWindWaveNS(0.671304d, 0.071742d, 0.842434d, 0.207586d);
    	setWindWaveEW(0.255107d, 0.859997d, 0.788891d, 0.245136d);
    }
}