
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving43 extends AbstractProvingMDPHelicopter {

    public HelicopterProving43(){
	super();
        setWindWaveNS(0.623287d, 0.689516d, 0.113146d, 0.121580d);
    	setWindWaveEW(0.906291d, 0.769853d, 0.919793d, 0.516700d);
    }
}