
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving31 extends AbstractProvingMDPHelicopter {

    public HelicopterProving31(){
	super();
        setWindWaveNS(0.794824d, 0.602225d, 0.263887d, 0.679451d);
    	setWindWaveEW(0.342866d, 0.479754d, 0.454708d, 0.488944d);
    }
}