
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving42 extends AbstractProvingMDPHelicopter {

    public HelicopterProving42(){
	super();
        setWindWaveNS(0.228065d, 0.037776d, 0.151385d, 0.766839d);
    	setWindWaveEW(0.762214d, 0.598520d, 0.346943d, 0.314467d);
    }
}