
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving41 extends AbstractProvingMDPHelicopter {

    public HelicopterProving41(){
	super();
        setWindWaveNS(0.910831d, 0.655745d, 0.730030d, 0.847293d);
    	setWindWaveEW(0.294718d, 0.691668d, 0.887693d, 0.736127d);
    }
}