
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving86 extends AbstractProvingMDPHelicopter {

    public HelicopterProving86(){
	super();
        setWindWaveNS(0.455209d, 0.064787d, 0.614944d, 0.751484d);
    	setWindWaveEW(0.178983d, 0.680585d, 0.815931d, 0.109685d);
    }
}