
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving67 extends AbstractProvingMDPHelicopter {

    public HelicopterProving67(){
	super();
        setWindWaveNS(0.689968d, 0.040413d, 0.188513d, 0.585989d);
    	setWindWaveEW(0.374834d, 0.974556d, 0.423513d, 0.344216d);
    }
}