
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving26 extends AbstractProvingMDPHelicopter {

    public HelicopterProving26(){
	super();
        setWindWaveNS(0.970205d, 0.775268d, 0.508313d, 0.852710d);
    	setWindWaveEW(0.096279d, 0.674491d, 0.618703d, 0.138173d);
    }
}