
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving87 extends AbstractProvingMDPHelicopter {

    public HelicopterProving87(){
	super();
        setWindWaveNS(0.764055d, 0.387437d, 0.767976d, 0.455900d);
    	setWindWaveEW(0.451879d, 0.811253d, 0.084213d, 0.933620d);
    }
}