
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving34 extends AbstractProvingMDPHelicopter {

    public HelicopterProving34(){
	super();
        setWindWaveNS(0.238092d, 0.201608d, 0.012875d, 0.725412d);
    	setWindWaveEW(0.719615d, 0.853043d, 0.993647d, 0.746141d);
    }
}