
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving98 extends AbstractProvingMDPHelicopter {

    public HelicopterProving98(){
	super();
        setWindWaveNS(0.992507d, 0.234669d, 0.240674d, 0.391493d);
    	setWindWaveEW(0.357763d, 0.697252d, 0.177835d, 0.861190d);
    }
}