
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving9 extends AbstractProvingMDPHelicopter {

    public HelicopterProving9(){
	super();
        setWindWaveNS(0.454859d, 0.659265d, 0.994785d, 0.264487d);
    	setWindWaveEW(0.328989d, 0.280465d, 0.633432d, 0.957884d);
    }
}