
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving46 extends AbstractProvingMDPHelicopter {

    public HelicopterProving46(){
	super();
        setWindWaveNS(0.713954d, 0.957944d, 0.840942d, 0.635438d);
    	setWindWaveEW(0.898121d, 0.608309d, 0.878158d, 0.572563d);
    }
}