
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving45 extends AbstractProvingMDPHelicopter {

    public HelicopterProving45(){
	super();
        setWindWaveNS(0.397420d, 0.740359d, 0.896164d, 0.578475d);
    	setWindWaveEW(0.811603d, 0.557959d, 0.306904d, 0.532663d);
    }
}