
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving54 extends AbstractProvingMDPHelicopter {

    public HelicopterProving54(){
	super();
        setWindWaveNS(0.964155d, 0.637166d, 0.598482d, 0.676548d);
    	setWindWaveEW(0.064790d, 0.072606d, 0.218208d, 0.843012d);
    }
}