
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving81 extends AbstractProvingMDPHelicopter {

    public HelicopterProving81(){
	super();
        setWindWaveNS(0.419169d, 0.023537d, 0.816767d, 0.014298d);
    	setWindWaveEW(0.595807d, 0.666992d, 0.664089d, 0.916185d);
    }
}