
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving24 extends AbstractProvingMDPHelicopter {

    public HelicopterProving24(){
	super();
        setWindWaveNS(0.453469d, 0.275309d, 0.267975d, 0.666288d);
    	setWindWaveEW(0.681077d, 0.308207d, 0.128389d, 0.038201d);
    }
}