
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving15 extends AbstractProvingMDPHelicopter {

    public HelicopterProving15(){
	super();
        setWindWaveNS(0.812598d, 0.995816d, 0.094286d, 0.565320d);
    	setWindWaveEW(0.177952d, 0.822956d, 0.676576d, 0.388392d);
    }
}