
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving65 extends AbstractProvingMDPHelicopter {

    public HelicopterProving65(){
	super();
        setWindWaveNS(0.219305d, 0.666023d, 0.482806d, 0.854667d);
    	setWindWaveEW(0.103197d, 0.821275d, 0.462760d, 0.823576d);
    }
}