
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving28 extends AbstractProvingMDPHelicopter {

    public HelicopterProving28(){
	super();
        setWindWaveNS(0.506611d, 0.591016d, 0.708118d, 0.594742d);
    	setWindWaveEW(0.780090d, 0.390038d, 0.902180d, 0.197434d);
    }
}