
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving59 extends AbstractProvingMDPHelicopter {

    public HelicopterProving59(){
	super();
        setWindWaveNS(0.809570d, 0.481525d, 0.200053d, 0.691785d);
    	setWindWaveEW(0.782968d, 0.750213d, 0.532390d, 0.241363d);
    }
}