
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving22 extends AbstractProvingMDPHelicopter {

    public HelicopterProving22(){
	super();
        setWindWaveNS(0.166033d, 0.674197d, 0.406838d, 0.202739d);
    	setWindWaveEW(0.930122d, 0.967673d, 0.183607d, 0.764010d);
    }
}