
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving99 extends AbstractProvingMDPHelicopter {

    public HelicopterProving99(){
	super();
        setWindWaveNS(0.255365d, 0.568530d, 0.808455d, 0.916835d);
    	setWindWaveEW(0.323799d, 0.314304d, 0.824353d, 0.215291d);
    }
}