
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving25 extends AbstractProvingMDPHelicopter {

    public HelicopterProving25(){
	super();
        setWindWaveNS(0.067518d, 0.583335d, 0.442623d, 0.584489d);
    	setWindWaveEW(0.074735d, 0.840171d, 0.970461d, 0.685279d);
    }
}