
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving92 extends AbstractProvingMDPHelicopter {

    public HelicopterProving92(){
	super();
        setWindWaveNS(0.595285d, 0.715323d, 0.746822d, 0.212276d);
    	setWindWaveEW(0.939465d, 0.389078d, 0.430160d, 0.606700d);
    }
}