
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving83 extends AbstractProvingMDPHelicopter {

    public HelicopterProving83(){
	super();
        setWindWaveNS(0.027018d, 0.550601d, 0.819082d, 0.014256d);
    	setWindWaveEW(0.529300d, 0.358727d, 0.093346d, 0.592129d);
    }
}