
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving66 extends AbstractProvingMDPHelicopter {

    public HelicopterProving66(){
	super();
        setWindWaveNS(0.135634d, 0.009331d, 0.147095d, 0.833721d);
    	setWindWaveEW(0.692817d, 0.198912d, 0.351833d, 0.470175d);
    }
}