
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving37 extends AbstractProvingMDPHelicopter {

    public HelicopterProving37(){
	super();
        setWindWaveNS(0.086955d, 0.356526d, 0.571790d, 0.083523d);
    	setWindWaveEW(0.034791d, 0.624530d, 0.761690d, 0.633064d);
    }
}