
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving47 extends AbstractProvingMDPHelicopter {

    public HelicopterProving47(){
	super();
        setWindWaveNS(0.621253d, 0.653171d, 0.550080d, 0.041626d);
    	setWindWaveEW(0.114202d, 0.500257d, 0.644984d, 0.762980d);
    }
}