
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving76 extends AbstractProvingMDPHelicopter {

    public HelicopterProving76(){
	super();
        setWindWaveNS(0.859176d, 0.122584d, 0.876657d, 0.140293d);
    	setWindWaveEW(0.255353d, 0.657723d, 0.711036d, 0.399624d);
    }
}