
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving2 extends AbstractProvingMDPHelicopter {

    public HelicopterProving2(){
	super();
        setWindWaveNS(0.026642d, 0.581025d, 0.736446d, 0.135444d);
    	setWindWaveEW(0.467535d, 0.305976d, 0.850620d, 0.235215d);
    }
}