
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving90 extends AbstractProvingMDPHelicopter {

    public HelicopterProving90(){
	super();
        setWindWaveNS(0.759001d, 0.180376d, 0.118433d, 0.614029d);
    	setWindWaveEW(0.919464d, 0.428969d, 0.801184d, 0.425194d);
    }
}