
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving39 extends AbstractProvingMDPHelicopter {

    public HelicopterProving39(){
	super();
        setWindWaveNS(0.247988d, 0.245745d, 0.797634d, 0.135491d);
    	setWindWaveEW(0.322483d, 0.093755d, 0.223999d, 0.109782d);
    }
}