
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving73 extends AbstractProvingMDPHelicopter {

    public HelicopterProving73(){
	super();
        setWindWaveNS(0.232655d, 0.518932d, 0.025681d, 0.170374d);
    	setWindWaveEW(0.519029d, 0.472686d, 0.220517d, 0.736550d);
    }
}