
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving79 extends AbstractProvingMDPHelicopter {

    public HelicopterProving79(){
	super();
        setWindWaveNS(0.359570d, 0.410658d, 0.629282d, 0.212900d);
    	setWindWaveEW(0.682622d, 0.577974d, 0.140912d, 0.199205d);
    }
}