
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving77 extends AbstractProvingMDPHelicopter {

    public HelicopterProving77(){
	super();
        setWindWaveNS(0.445731d, 0.854616d, 0.250419d, 0.638212d);
    	setWindWaveEW(0.662736d, 0.891561d, 0.134239d, 0.036768d);
    }
}