
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving69 extends AbstractProvingMDPHelicopter {

    public HelicopterProving69(){
	super();
        setWindWaveNS(0.761977d, 0.604944d, 0.382924d, 0.507431d);
    	setWindWaveEW(0.565850d, 0.063309d, 0.411827d, 0.344914d);
    }
}