
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving11 extends AbstractProvingMDPHelicopter {

    public HelicopterProving11(){
	super();
        setWindWaveNS(0.775543d, 0.076373d, 0.777830d, 0.513948d);
    	setWindWaveEW(0.878516d, 0.036489d, 0.344884d, 0.063401d);
    }
}