
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving14 extends AbstractProvingMDPHelicopter {

    public HelicopterProving14(){
	super();
        setWindWaveNS(0.709463d, 0.808536d, 0.538003d, 0.942553d);
    	setWindWaveEW(0.708912d, 0.390587d, 0.868717d, 0.297878d);
    }
}