
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving72 extends AbstractProvingMDPHelicopter {

    public HelicopterProving72(){
	super();
        setWindWaveNS(0.412477d, 0.869057d, 0.355800d, 0.060808d);
    	setWindWaveEW(0.093678d, 0.035722d, 0.069272d, 0.316335d);
    }
}