
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving38 extends AbstractProvingMDPHelicopter {

    public HelicopterProving38(){
	super();
        setWindWaveNS(0.184903d, 0.280350d, 0.112370d, 0.114452d);
    	setWindWaveEW(0.636940d, 0.684777d, 0.128471d, 0.477012d);
    }
}