
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving80 extends AbstractProvingMDPHelicopter {

    public HelicopterProving80(){
	super();
        setWindWaveNS(0.816408d, 0.123992d, 0.537098d, 0.473021d);
    	setWindWaveEW(0.891800d, 0.694927d, 0.765248d, 0.571317d);
    }
}