
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving93 extends AbstractProvingMDPHelicopter {

    public HelicopterProving93(){
	super();
        setWindWaveNS(0.103910d, 0.002035d, 0.293472d, 0.301366d);
    	setWindWaveEW(0.712164d, 0.700093d, 0.169723d, 0.899686d);
    }
}