
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving62 extends AbstractProvingMDPHelicopter {

    public HelicopterProving62(){
	super();
        setWindWaveNS(0.718555d, 0.107957d, 0.206715d, 0.231776d);
    	setWindWaveEW(0.204271d, 0.797368d, 0.314566d, 0.820761d);
    }
}