
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving3 extends AbstractProvingMDPHelicopter {

    public HelicopterProving3(){
	super();
        setWindWaveNS(0.180070d, 0.625150d, 0.023515d, 0.588239d);
    	setWindWaveEW(0.106347d, 0.902646d, 0.009704d, 0.600568d);
    }
}