
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving60 extends AbstractProvingMDPHelicopter {

    public HelicopterProving60(){
	super();
        setWindWaveNS(0.645361d, 0.686194d, 0.025075d, 0.705051d);
    	setWindWaveEW(0.035982d, 0.093458d, 0.010024d, 0.218058d);
    }
}