
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving82 extends AbstractProvingMDPHelicopter {

    public HelicopterProving82(){
	super();
        setWindWaveNS(0.062808d, 0.244279d, 0.729722d, 0.949783d);
    	setWindWaveEW(0.116630d, 0.348769d, 0.231983d, 0.848212d);
    }
}