
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving33 extends AbstractProvingMDPHelicopter {

    public HelicopterProving33(){
	super();
        setWindWaveNS(0.716873d, 0.193907d, 0.061474d, 0.267158d);
    	setWindWaveEW(0.071126d, 0.965855d, 0.536045d, 0.909678d);
    }
}