
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving30 extends AbstractProvingMDPHelicopter {

    public HelicopterProving30(){
	super();
        setWindWaveNS(0.989782d, 0.020154d, 0.496865d, 0.787617d);
    	setWindWaveEW(0.948428d, 0.636791d, 0.192412d, 0.203433d);
    }
}