
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving97 extends AbstractProvingMDPHelicopter {

    public HelicopterProving97(){
	super();
        setWindWaveNS(0.369084d, 0.158649d, 0.017320d, 0.836244d);
    	setWindWaveEW(0.122587d, 0.962126d, 0.457031d, 0.173080d);
    }
}