
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving53 extends AbstractProvingMDPHelicopter {

    public HelicopterProving53(){
	super();
        setWindWaveNS(0.920087d, 0.365397d, 0.822918d, 0.137482d);
    	setWindWaveEW(0.418359d, 0.303045d, 0.229936d, 0.797525d);
    }
}