
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving95 extends AbstractProvingMDPHelicopter {

    public HelicopterProving95(){
	super();
        setWindWaveNS(0.207090d, 0.995771d, 0.799309d, 0.069385d);
    	setWindWaveEW(0.716462d, 0.935323d, 0.327637d, 0.984232d);
    }
}