
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving50 extends AbstractProvingMDPHelicopter {

    public HelicopterProving50(){
	super();
        setWindWaveNS(0.708069d, 0.216841d, 0.558807d, 0.699944d);
    	setWindWaveEW(0.386974d, 0.819303d, 0.117240d, 0.612828d);
    }
}