
/*
 * This code was auto-generated by the parameter script makeMDP.py.
 * Do not change these values manually.
 */
package org.rlcommunity.environment.helicopter.proving;

public class HelicopterProving94 extends AbstractProvingMDPHelicopter {

    public HelicopterProving94(){
	super();
        setWindWaveNS(0.865401d, 0.915439d, 0.604375d, 0.222851d);
    	setWindWaveEW(0.776132d, 0.967096d, 0.501639d, 0.411559d);
    }
}