import GenParamSamples


# see gen param samples for explanation on parameters

method1 = "setCompetition"
method2 = "setRandomStarts"
method3 = "setCompetitionParams"

f = open('./src/org/rlcommunity/environment/GeneralizedAcrobot/GenAcrobotParamData.java','w')

f.write("""
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package org.rlcommunity.environment.generalizedacrobot;

public class GenAcrobotParamData {

    void setParameters(int ParamSet, GeneralizedAcrobot thisEnvironment) {
        switch (ParamSet) {""")
str_option= """
            case 0:
                double p0[] = {1.0d,0.05d,1.0d,1.0d,0.0d,0.0d,0.0d,0.0d};
                System.out.println("Selected Standard Acrobot");
                thisEnvironment.setCompetition(false);
                thisEnvironment.setRandomStarts(false);
                thisEnvironment.setCompetitionParams( p0 );              
                break;"""         
f.write(str_option)
        
for i in range(1,40):
        str_option= """
            case %d:
                double p%d[] = {%f , %f , %f , %f , %f , %f , %f , %f };
                thisEnvironment.setCompetition(true);
                thisEnvironment.setRandomStarts(true);
                thisEnvironment.setCompetitionParams( p%d );              
                break;""" % (i,i, GenParamSamples.sampleP1(i), GenParamSamples.sampleP2(i),GenParamSamples.sampleP3(i),GenParamSamples.sampleP4(i),GenParamSamples.sampleP5(i),GenParamSamples.sampleP6(i),GenParamSamples.sampleP7(i),GenParamSamples.sampleP8(i),i )
        print str_option
        f.write(str_option)
        
f.write("""
            default:
                System.err.println("Invalid Parameter Set Requested ("+ParamSet+") : using Param Set 0");
                setParameters(0, thisEnvironment);
        }
    }
}""")
f.close()
