import GenParamSamples
import os

# for params info see GenParamSamples


method1 = "setCompetition"
method2 = "setRandomStarts"
method3 = "setCompetitionParams"

#f = open('./src/org/rlcommunity/environment/GeneralizedAcrobot/GenAcrobotParamData.java','w')

try:
    os.mkdir('./src/org/rlcommunity/environment/testing')
except:
    pass
    
for i in range(1,26):    
    f = open('./src/org/rlcommunity/environment/testing/AcrobotTesting%d.java'%i ,'w')

    f.write("""
//package org.rlcommunity.environment.testing;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotTesting%d extends AbstractProvingMDPAcrobot {

    public AcrobotTesting%d() {
        super();
        double p[] = {%f , %f , %f , %f , %f , %f , %f , %f };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        """ % (i,i, GenParamSamples.sampleP1(i), GenParamSamples.sampleP2(i),GenParamSamples.sampleP3(i),GenParamSamples.sampleP4(i),GenParamSamples.sampleP5(i),GenParamSamples.sampleP6(i),GenParamSamples.sampleP7(i),GenParamSamples.sampleP8(i) ))

    f.close()
