
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP65;

import GeneralizedHelicopter.*;

public class HPMDP65 extends AbstractProvingMDPHelicopter{

    public HPMDP65(){
	super();
        setWind0(-0.646846d);
    	setWind1(0.802977d);
    }
}