
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package GeneralizedMountainCar;

public class GenMCParamData {

    void setParameters(int ParamSet, GeneralizedMountainCar thisEnvironment) {
        switch (ParamSet) {
            case 0:
                thisEnvironment.setScaleP(0.290579d);
                thisEnvironment.setScaleV(0.508588d);
                thisEnvironment.setPOffset(0.942734d);
                thisEnvironment.setVOffset(-0.914592d);
                thisEnvironment.setPNoiseDivider(7.000232d);
                thisEnvironment.setVNoiseDivider(5.404274d);
                thisEnvironment.setAccelBiasMean(1.058032d);
                break;
            case 1:
                thisEnvironment.setScaleP(0.686332d);
                thisEnvironment.setScaleV(0.645236d);
                thisEnvironment.setPOffset(-0.176211d);
                thisEnvironment.setVOffset(0.654121d);
                thisEnvironment.setPNoiseDivider(6.815142d);
                thisEnvironment.setVNoiseDivider(7.371020d);
                thisEnvironment.setAccelBiasMean(0.871969d);
                break;
            case 2:
                thisEnvironment.setScaleP(0.251273d);
                thisEnvironment.setScaleV(0.408204d);
                thisEnvironment.setPOffset(-0.564551d);
                thisEnvironment.setVOffset(0.736439d);
                thisEnvironment.setPNoiseDivider(18.686008d);
                thisEnvironment.setVNoiseDivider(10.430101d);
                thisEnvironment.setAccelBiasMean(0.843165d);
                break;
            case 3:
                thisEnvironment.setScaleP(0.733766d);
                thisEnvironment.setScaleV(0.630232d);
                thisEnvironment.setPOffset(0.273770d);
                thisEnvironment.setVOffset(-0.055226d);
                thisEnvironment.setPNoiseDivider(6.374249d);
                thisEnvironment.setVNoiseDivider(9.869309d);
                thisEnvironment.setAccelBiasMean(1.092968d);
                break;
            case 4:
                thisEnvironment.setScaleP(0.378139d);
                thisEnvironment.setScaleV(0.671418d);
                thisEnvironment.setPOffset(0.921198d);
                thisEnvironment.setVOffset(-0.904825d);
                thisEnvironment.setPNoiseDivider(16.619865d);
                thisEnvironment.setVNoiseDivider(5.468835d);
                thisEnvironment.setAccelBiasMean(0.968126d);
                break;
            case 5:
                thisEnvironment.setScaleP(0.559191d);
                thisEnvironment.setScaleV(0.803760d);
                thisEnvironment.setPOffset(0.071427d);
                thisEnvironment.setVOffset(0.844936d);
                thisEnvironment.setPNoiseDivider(15.417077d);
                thisEnvironment.setVNoiseDivider(14.878142d);
                thisEnvironment.setAccelBiasMean(0.998256d);
                break;
            case 6:
                thisEnvironment.setScaleP(0.378252d);
                thisEnvironment.setScaleV(0.683495d);
                thisEnvironment.setPOffset(-0.978952d);
                thisEnvironment.setVOffset(-0.970474d);
                thisEnvironment.setPNoiseDivider(7.441317d);
                thisEnvironment.setVNoiseDivider(13.416113d);
                thisEnvironment.setAccelBiasMean(1.023905d);
                break;
            case 7:
                thisEnvironment.setScaleP(0.615214d);
                thisEnvironment.setScaleV(0.632031d);
                thisEnvironment.setPOffset(0.704492d);
                thisEnvironment.setVOffset(-0.020670d);
                thisEnvironment.setPNoiseDivider(15.295898d);
                thisEnvironment.setVNoiseDivider(6.876872d);
                thisEnvironment.setAccelBiasMean(0.907519d);
                break;
            case 8:
                thisEnvironment.setScaleP(0.902579d);
                thisEnvironment.setScaleV(0.765098d);
                thisEnvironment.setPOffset(0.990991d);
                thisEnvironment.setVOffset(-0.530052d);
                thisEnvironment.setPNoiseDivider(5.518585d);
                thisEnvironment.setVNoiseDivider(14.738578d);
                thisEnvironment.setAccelBiasMean(0.960999d);
                break;
            case 9:
                thisEnvironment.setScaleP(0.879246d);
                thisEnvironment.setScaleV(0.581836d);
                thisEnvironment.setPOffset(0.714740d);
                thisEnvironment.setVOffset(-0.922149d);
                thisEnvironment.setPNoiseDivider(9.540068d);
                thisEnvironment.setVNoiseDivider(14.741427d);
                thisEnvironment.setAccelBiasMean(0.966304d);
                break;
            case 10:
                thisEnvironment.setScaleP(0.457631d);
                thisEnvironment.setScaleV(0.692917d);
                thisEnvironment.setPOffset(-0.201220d);
                thisEnvironment.setVOffset(0.789859d);
                thisEnvironment.setPNoiseDivider(7.736094d);
                thisEnvironment.setVNoiseDivider(12.418090d);
                thisEnvironment.setAccelBiasMean(0.940247d);
                break;
            case 11:
                thisEnvironment.setScaleP(0.816728d);
                thisEnvironment.setScaleV(0.663534d);
                thisEnvironment.setPOffset(0.748141d);
                thisEnvironment.setVOffset(0.843973d);
                thisEnvironment.setPNoiseDivider(13.367033d);
                thisEnvironment.setVNoiseDivider(8.661633d);
                thisEnvironment.setAccelBiasMean(0.907132d);
                break;
            case 12:
                thisEnvironment.setScaleP(0.463377d);
                thisEnvironment.setScaleV(0.462716d);
                thisEnvironment.setPOffset(-0.360285d);
                thisEnvironment.setVOffset(0.925316d);
                thisEnvironment.setPNoiseDivider(19.100358d);
                thisEnvironment.setVNoiseDivider(16.289273d);
                thisEnvironment.setAccelBiasMean(1.149860d);
                break;
            case 13:
                thisEnvironment.setScaleP(0.482191d);
                thisEnvironment.setScaleV(0.428408d);
                thisEnvironment.setPOffset(-0.750851d);
                thisEnvironment.setVOffset(-0.203256d);
                thisEnvironment.setPNoiseDivider(17.705143d);
                thisEnvironment.setVNoiseDivider(10.944705d);
                thisEnvironment.setAccelBiasMean(1.039298d);
                break;
            case 14:
                thisEnvironment.setScaleP(0.667479d);
                thisEnvironment.setScaleV(0.440700d);
                thisEnvironment.setPOffset(0.067986d);
                thisEnvironment.setVOffset(-0.637870d);
                thisEnvironment.setPNoiseDivider(12.800892d);
                thisEnvironment.setVNoiseDivider(11.075084d);
                thisEnvironment.setAccelBiasMean(1.086402d);
                break;
            case 15:
                thisEnvironment.setScaleP(0.372977d);
                thisEnvironment.setScaleV(0.994734d);
                thisEnvironment.setPOffset(-0.656542d);
                thisEnvironment.setVOffset(0.440516d);
                thisEnvironment.setPNoiseDivider(17.477973d);
                thisEnvironment.setVNoiseDivider(14.534006d);
                thisEnvironment.setAccelBiasMean(0.832636d);
                break;
            case 16:
                thisEnvironment.setScaleP(0.495824d);
                thisEnvironment.setScaleV(0.309824d);
                thisEnvironment.setPOffset(0.400975d);
                thisEnvironment.setVOffset(0.176481d);
                thisEnvironment.setPNoiseDivider(12.282364d);
                thisEnvironment.setVNoiseDivider(12.262763d);
                thisEnvironment.setAccelBiasMean(0.957735d);
                break;
            case 17:
                thisEnvironment.setScaleP(0.693542d);
                thisEnvironment.setScaleV(0.567091d);
                thisEnvironment.setPOffset(0.824925d);
                thisEnvironment.setVOffset(0.151551d);
                thisEnvironment.setPNoiseDivider(19.222296d);
                thisEnvironment.setVNoiseDivider(7.724898d);
                thisEnvironment.setAccelBiasMean(0.914458d);
                break;
            case 18:
                thisEnvironment.setScaleP(0.605331d);
                thisEnvironment.setScaleV(0.740806d);
                thisEnvironment.setPOffset(0.100337d);
                thisEnvironment.setVOffset(0.525166d);
                thisEnvironment.setPNoiseDivider(7.279610d);
                thisEnvironment.setVNoiseDivider(18.399417d);
                thisEnvironment.setAccelBiasMean(1.049788d);
                break;
            case 19:
                thisEnvironment.setScaleP(0.556020d);
                thisEnvironment.setScaleV(0.677983d);
                thisEnvironment.setPOffset(0.634869d);
                thisEnvironment.setVOffset(0.940825d);
                thisEnvironment.setPNoiseDivider(5.668726d);
                thisEnvironment.setVNoiseDivider(15.000440d);
                thisEnvironment.setAccelBiasMean(0.975483d);
                break;
            case 20:
                thisEnvironment.setScaleP(0.810809d);
                thisEnvironment.setScaleV(0.303628d);
                thisEnvironment.setPOffset(-0.552167d);
                thisEnvironment.setVOffset(0.810273d);
                thisEnvironment.setPNoiseDivider(12.667548d);
                thisEnvironment.setVNoiseDivider(14.225362d);
                thisEnvironment.setAccelBiasMean(1.059751d);
                break;
            case 21:
                thisEnvironment.setScaleP(0.684717d);
                thisEnvironment.setScaleV(0.775938d);
                thisEnvironment.setPOffset(0.553379d);
                thisEnvironment.setVOffset(0.431366d);
                thisEnvironment.setPNoiseDivider(10.412819d);
                thisEnvironment.setVNoiseDivider(13.820527d);
                thisEnvironment.setAccelBiasMean(0.965327d);
                break;
            case 22:
                thisEnvironment.setScaleP(0.660269d);
                thisEnvironment.setScaleV(0.516859d);
                thisEnvironment.setPOffset(-0.355230d);
                thisEnvironment.setVOffset(0.580876d);
                thisEnvironment.setPNoiseDivider(9.776336d);
                thisEnvironment.setVNoiseDivider(7.588879d);
                thisEnvironment.setAccelBiasMean(0.966155d);
                break;
            case 23:
                thisEnvironment.setScaleP(0.883277d);
                thisEnvironment.setScaleV(0.810328d);
                thisEnvironment.setPOffset(0.006568d);
                thisEnvironment.setVOffset(-0.984100d);
                thisEnvironment.setPNoiseDivider(5.499769d);
                thisEnvironment.setVNoiseDivider(17.739546d);
                thisEnvironment.setAccelBiasMean(0.886035d);
                break;
            case 24:
                thisEnvironment.setScaleP(0.440685d);
                thisEnvironment.setScaleV(0.925506d);
                thisEnvironment.setPOffset(-0.006381d);
                thisEnvironment.setVOffset(-0.523560d);
                thisEnvironment.setPNoiseDivider(10.827697d);
                thisEnvironment.setVNoiseDivider(13.936132d);
                thisEnvironment.setAccelBiasMean(1.052741d);
                break;
            case 25:
                thisEnvironment.setScaleP(0.783144d);
                thisEnvironment.setScaleV(0.454201d);
                thisEnvironment.setPOffset(0.370253d);
                thisEnvironment.setVOffset(-0.193791d);
                thisEnvironment.setPNoiseDivider(13.147122d);
                thisEnvironment.setVNoiseDivider(16.485853d);
                thisEnvironment.setAccelBiasMean(0.828394d);
                break;
            case 26:
                thisEnvironment.setScaleP(0.719780d);
                thisEnvironment.setScaleV(0.362691d);
                thisEnvironment.setPOffset(-0.917634d);
                thisEnvironment.setVOffset(-0.413783d);
                thisEnvironment.setPNoiseDivider(17.075779d);
                thisEnvironment.setVNoiseDivider(8.598877d);
                thisEnvironment.setAccelBiasMean(1.077620d);
                break;
            case 27:
                thisEnvironment.setScaleP(0.772963d);
                thisEnvironment.setScaleV(0.496723d);
                thisEnvironment.setPOffset(0.804458d);
                thisEnvironment.setVOffset(-0.577870d);
                thisEnvironment.setPNoiseDivider(12.655536d);
                thisEnvironment.setVNoiseDivider(13.675542d);
                thisEnvironment.setAccelBiasMean(0.957559d);
                break;
            case 28:
                thisEnvironment.setScaleP(0.457792d);
                thisEnvironment.setScaleV(0.834538d);
                thisEnvironment.setPOffset(-0.563265d);
                thisEnvironment.setVOffset(0.730753d);
                thisEnvironment.setPNoiseDivider(8.268912d);
                thisEnvironment.setVNoiseDivider(15.858341d);
                thisEnvironment.setAccelBiasMean(0.856771d);
                break;
            case 29:
                thisEnvironment.setScaleP(0.269242d);
                thisEnvironment.setScaleV(0.320556d);
                thisEnvironment.setPOffset(-0.031270d);
                thisEnvironment.setVOffset(-0.646795d);
                thisEnvironment.setPNoiseDivider(18.463580d);
                thisEnvironment.setVNoiseDivider(8.879999d);
                thisEnvironment.setAccelBiasMean(0.828851d);
                break;
            case 30:
                thisEnvironment.setScaleP(0.891033d);
                thisEnvironment.setScaleV(0.470912d);
                thisEnvironment.setPOffset(-0.961664d);
                thisEnvironment.setVOffset(0.480959d);
                thisEnvironment.setPNoiseDivider(19.006447d);
                thisEnvironment.setVNoiseDivider(10.430166d);
                thisEnvironment.setAccelBiasMean(1.186021d);
                break;
            case 31:
                thisEnvironment.setScaleP(0.396125d);
                thisEnvironment.setScaleV(0.356461d);
                thisEnvironment.setPOffset(0.536537d);
                thisEnvironment.setVOffset(-0.447614d);
                thisEnvironment.setPNoiseDivider(14.508256d);
                thisEnvironment.setVNoiseDivider(5.378156d);
                thisEnvironment.setAccelBiasMean(0.983580d);
                break;
            case 32:
                thisEnvironment.setScaleP(0.673265d);
                thisEnvironment.setScaleV(0.451243d);
                thisEnvironment.setPOffset(0.757643d);
                thisEnvironment.setVOffset(0.472217d);
                thisEnvironment.setPNoiseDivider(14.424354d);
                thisEnvironment.setVNoiseDivider(17.184167d);
                thisEnvironment.setAccelBiasMean(0.953162d);
                break;
            case 33:
                thisEnvironment.setScaleP(0.928731d);
                thisEnvironment.setScaleV(0.997678d);
                thisEnvironment.setPOffset(0.137768d);
                thisEnvironment.setVOffset(0.400541d);
                thisEnvironment.setPNoiseDivider(9.038177d);
                thisEnvironment.setVNoiseDivider(6.644022d);
                thisEnvironment.setAccelBiasMean(1.029809d);
                break;
            case 34:
                thisEnvironment.setScaleP(0.271446d);
                thisEnvironment.setScaleV(0.782170d);
                thisEnvironment.setPOffset(0.580466d);
                thisEnvironment.setVOffset(0.647778d);
                thisEnvironment.setPNoiseDivider(12.726983d);
                thisEnvironment.setVNoiseDivider(7.320774d);
                thisEnvironment.setAccelBiasMean(0.870248d);
                break;
            default:
                System.err.println("Invalid Parameter Set Requested ("+ParamSet+") : using Param Set 0");
                setParameters(0, thisEnvironment);
        }
    }
}