
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP96;

import GeneralizedHelicopter.*;

public class HPMDP96 extends AbstractProvingMDPHelicopter{

    public HPMDP96(){
	super();
        setWind0(-0.066333d);
    	setWind1(0.605705d);
    }
}