
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP59;

import GeneralizedHelicopter.*;

public class HPMDP59 extends AbstractProvingMDPHelicopter{

    public HPMDP59(){
	super();
        setWind0(-0.619700d);
    	setWind1(-0.684330d);
    }
}