
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP34;

import GeneralizedHelicopter.*;

public class HPMDP34 extends AbstractProvingMDPHelicopter{

    public HPMDP34(){
	super();
        setWind0(0.842566d);
    	setWind1(0.573594d);
    }
}