
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP10;

import GeneralizedHelicopter.*;

public class HPMDP10 extends AbstractProvingMDPHelicopter{

    public HPMDP10(){
	super();
        setWind0(0.746260d);
    	setWind1(-0.167417d);
    }
}