
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP41;

import GeneralizedHelicopter.*;

public class HPMDP41 extends AbstractProvingMDPHelicopter{

    public HPMDP41(){
	super();
        setWind0(0.161959d);
    	setWind1(0.060760d);
    }
}