
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP72;

import GeneralizedHelicopter.*;

public class HPMDP72 extends AbstractProvingMDPHelicopter{

    public HPMDP72(){
	super();
        setWind0(0.553304d);
    	setWind1(-0.817504d);
    }
}