
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP31;

import GeneralizedHelicopter.*;

public class HPMDP31 extends AbstractProvingMDPHelicopter{

    public HPMDP31(){
	super();
        setWind0(0.502846d);
    	setWind1(-0.348230d);
    }
}