
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP64;

import GeneralizedHelicopter.*;

public class HPMDP64 extends AbstractProvingMDPHelicopter{

    public HPMDP64(){
	super();
        setWind0(-0.579050d);
    	setWind1(0.137871d);
    }
}