
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP77;

import GeneralizedHelicopter.*;

public class HPMDP77 extends AbstractProvingMDPHelicopter{

    public HPMDP77(){
	super();
        setWind0(0.739787d);
    	setWind1(0.112989d);
    }
}