
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP70;

import GeneralizedHelicopter.*;

public class HPMDP70 extends AbstractProvingMDPHelicopter{

    public HPMDP70(){
	super();
        setWind0(0.159520d);
    	setWind1(-0.094063d);
    }
}