
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP12;

import GeneralizedHelicopter.*;

public class HPMDP12 extends AbstractProvingMDPHelicopter{

    public HPMDP12(){
	super();
        setWind0(-0.518763d);
    	setWind1(-0.531468d);
    }
}