
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP37;

import GeneralizedHelicopter.*;

public class HPMDP37 extends AbstractProvingMDPHelicopter{

    public HPMDP37(){
	super();
        setWind0(0.000431d);
    	setWind1(-0.466892d);
    }
}