
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP56;

import GeneralizedHelicopter.*;

public class HPMDP56 extends AbstractProvingMDPHelicopter{

    public HPMDP56(){
	super();
        setWind0(-0.630552d);
    	setWind1(0.396823d);
    }
}