
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP79;

import GeneralizedHelicopter.*;

public class HPMDP79 extends AbstractProvingMDPHelicopter{

    public HPMDP79(){
	super();
        setWind0(-0.793942d);
    	setWind1(-0.631749d);
    }
}