
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP46;

import GeneralizedHelicopter.*;

public class HPMDP46 extends AbstractProvingMDPHelicopter{

    public HPMDP46(){
	super();
        setWind0(0.198432d);
    	setWind1(-0.714164d);
    }
}