
//package org.rlcommunity.environment.proving;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotProving31 extends AbstractProvingMDPAcrobot {

    public AcrobotProving31() {
        super();
        double p[] = {1.800000 , 0.070000 , 0.699171 , 0.823512 , 2.562393 , -0.100393 , 0.063464 , -0.191247 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        