
//package org.rlcommunity.environment.proving;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotProving27 extends AbstractProvingMDPAcrobot {

    public AcrobotProving27() {
        super();
        double p[] = {1.800000 , 0.080000 , 0.116834 , 0.834346 , -0.441711 , -1.745303 , -0.029998 , 0.448158 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        