
//package org.rlcommunity.environment.proving;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotProving2 extends AbstractProvingMDPAcrobot {

    public AcrobotProving2() {
        super();
        double p[] = {1.000000 , 0.080000 , 0.284171 , 0.578883 , 0.006203 , -0.136521 , -0.093373 , 0.346529 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        