
//package org.rlcommunity.environment.proving;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotProving48 extends AbstractProvingMDPAcrobot {

    public AcrobotProving48() {
        super();
        double p[] = {1.100000 , 0.010000 , 0.786454 , 0.218587 , 2.509975 , -2.958950 , 0.496111 , 0.224703 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        