
//package org.rlcommunity.environment.proving;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotProving43 extends AbstractProvingMDPAcrobot {

    public AcrobotProving43() {
        super();
        double p[] = {1.100000 , 0.080000 , 0.601544 , 0.453256 , 1.840653 , -2.806700 , -0.202139 , 0.192139 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        