
//package org.rlcommunity.environment.proving;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotProving21 extends AbstractProvingMDPAcrobot {

    public AcrobotProving21() {
        super();
        double p[] = {0.900000 , 0.070000 , 0.719272 , 0.875771 , 0.041343 , -1.637263 , 0.154036 , 0.833788 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        