
//package org.rlcommunity.environment.proving;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotProving20 extends AbstractProvingMDPAcrobot {

    public AcrobotProving20() {
        super();
        double p[] = {1.500000 , 0.090000 , 0.305193 , 0.324685 , 1.254445 , -2.121124 , 0.164281 , -0.549785 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        