
//package org.rlcommunity.environment.proving;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotProving9 extends AbstractProvingMDPAcrobot {

    public AcrobotProving9() {
        super();
        double p[] = {1.500000 , 0.040000 , 0.180753 , 0.257635 , -1.193530 , 2.200832 , -0.571534 , -0.585836 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        