
//package org.rlcommunity.environment.proving;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotProving3 extends AbstractProvingMDPAcrobot {

    public AcrobotProving3() {
        super();
        double p[] = {1.100000 , 0.080000 , 0.203669 , 0.997707 , -1.955450 , -1.831867 , -0.142574 , 0.743992 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        