
//package org.rlcommunity.environment.proving;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotProving29 extends AbstractProvingMDPAcrobot {

    public AcrobotProving29() {
        super();
        double p[] = {1.200000 , 0.080000 , 0.699060 , 0.406031 , -0.156066 , -2.827489 , 0.550688 , 0.620520 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        