
//package org.rlcommunity.environment.proving;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotProving11 extends AbstractProvingMDPAcrobot {

    public AcrobotProving11() {
        super();
        double p[] = {1.100000 , 0.040000 , 0.425289 , 0.602692 , -0.636292 , -1.766899 , -0.014380 , 0.869546 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        