
//package org.rlcommunity.environment.proving;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotProving28 extends AbstractProvingMDPAcrobot {

    public AcrobotProving28() {
        super();
        double p[] = {1.000000 , 0.080000 , 0.996600 , 0.955986 , -1.640748 , -1.321315 , 0.863571 , 0.022686 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        