
//package org.rlcommunity.environment.proving;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotProving25 extends AbstractProvingMDPAcrobot {

    public AcrobotProving25() {
        super();
        double p[] = {1.700000 , 0.070000 , 0.889198 , 0.361820 , -3.051009 , -2.093957 , 0.632997 , 0.899126 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        