
//package org.rlcommunity.environment.proving;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotProving16 extends AbstractProvingMDPAcrobot {

    public AcrobotProving16() {
        super();
        double p[] = {1.000000 , 0.070000 , 0.770837 , 0.733164 , -2.542079 , -2.828360 , 0.102752 , -0.813092 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        