
//package org.rlcommunity.environment.proving;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotProving44 extends AbstractProvingMDPAcrobot {

    public AcrobotProving44() {
        super();
        double p[] = {0.900000 , 0.090000 , 0.838818 , 0.825309 , 1.306813 , 2.234454 , -0.988967 , 0.590640 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        