
//package org.rlcommunity.environment.proving;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotProving10 extends AbstractProvingMDPAcrobot {

    public AcrobotProving10() {
        super();
        double p[] = {1.900000 , 0.040000 , 0.169257 , 0.431401 , -0.947905 , -0.760031 , 0.109456 , -0.552567 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        