
//package org.rlcommunity.environment.proving;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotProving38 extends AbstractProvingMDPAcrobot {

    public AcrobotProving38() {
        super();
        double p[] = {1.400000 , 0.070000 , 0.182665 , 0.341010 , 1.471878 , 1.165959 , 0.299881 , -0.472519 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        