
//package org.rlcommunity.environment.proving;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotProving35 extends AbstractProvingMDPAcrobot {

    public AcrobotProving35() {
        super();
        double p[] = {1.400000 , 0.040000 , 0.321707 , 0.197019 , -0.270928 , 2.741037 , 0.376993 , 0.322227 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        