
//package org.rlcommunity.environment.proving;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotProving33 extends AbstractProvingMDPAcrobot {

    public AcrobotProving33() {
        super();
        double p[] = {1.200000 , 0.060000 , 0.954095 , 0.147580 , 0.327225 , -2.900235 , 0.816587 , -0.515560 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        