
//package org.rlcommunity.environment.proving;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotProving36 extends AbstractProvingMDPAcrobot {

    public AcrobotProving36() {
        super();
        double p[] = {1.400000 , 0.040000 , 0.998161 , 0.710265 , 1.215628 , 0.526576 , -0.991896 , 1.003373 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        