
//package org.rlcommunity.environment.proving;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotProving32 extends AbstractProvingMDPAcrobot {

    public AcrobotProving32() {
        super();
        double p[] = {1.400000 , 0.020000 , 0.435913 , 0.193760 , 2.494428 , -3.087928 , -0.868188 , -0.214196 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        