
//package org.rlcommunity.environment.proving;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotProving24 extends AbstractProvingMDPAcrobot {

    public AcrobotProving24() {
        super();
        double p[] = {1.100000 , 0.080000 , 0.545179 , 0.473326 , -1.504507 , 2.785960 , -0.089439 , 0.948544 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        