
//package org.rlcommunity.environment.proving;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotProving6 extends AbstractProvingMDPAcrobot {

    public AcrobotProving6() {
        super();
        double p[] = {0.800000 , 0.060000 , 0.804428 , 0.165480 , 2.615098 , -0.004273 , 0.853887 , -0.619169 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        