
//package org.rlcommunity.environment.proving;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotProving30 extends AbstractProvingMDPAcrobot {

    public AcrobotProving30() {
        super();
        double p[] = {1.400000 , 0.040000 , 0.948848 , 0.243862 , 0.936955 , 3.137647 , 0.297717 , 0.354691 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        