
//package org.rlcommunity.environment.proving;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotProving23 extends AbstractProvingMDPAcrobot {

    public AcrobotProving23() {
        super();
        double p[] = {1.000000 , 0.090000 , 0.100249 , 0.214510 , 0.907064 , -1.954941 , 0.085538 , -0.843284 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        