
//package org.rlcommunity.environment.proving;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotProving39 extends AbstractProvingMDPAcrobot {

    public AcrobotProving39() {
        super();
        double p[] = {1.500000 , 0.060000 , 0.359605 , 0.585610 , -0.403905 , -1.335363 , 0.288201 , 0.877068 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        