
//package org.rlcommunity.environment.proving;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotProving14 extends AbstractProvingMDPAcrobot {

    public AcrobotProving14() {
        super();
        double p[] = {0.800000 , 0.040000 , 0.477872 , 0.801346 , 2.488110 , 2.861500 , -0.460311 , -0.249260 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        