
//package org.rlcommunity.environment.proving;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotProving4 extends AbstractProvingMDPAcrobot {

    public AcrobotProving4() {
        super();
        double p[] = {1.600000 , 0.060000 , 0.703250 , 0.648995 , 0.321054 , 1.775461 , -0.870906 , -0.317018 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        