
//package org.rlcommunity.environment.proving;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotProving7 extends AbstractProvingMDPAcrobot {

    public AcrobotProving7() {
        super();
        double p[] = {1.800000 , 0.070000 , 0.779042 , 0.151093 , 1.054418 , -1.266497 , -0.302403 , 0.469877 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        