
//package org.rlcommunity.environment.proving;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotProving45 extends AbstractProvingMDPAcrobot {

    public AcrobotProving45() {
        super();
        double p[] = {0.900000 , 0.010000 , 0.110289 , 0.301966 , 0.116861 , 2.316624 , -0.832156 , 0.300872 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        