
//package org.rlcommunity.environment.proving;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotProving49 extends AbstractProvingMDPAcrobot {

    public AcrobotProving49() {
        super();
        double p[] = {1.100000 , 0.040000 , 0.387533 , 0.506290 , 1.027285 , -1.349697 , -0.856690 , -0.089502 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        