
//package org.rlcommunity.environment.proving;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotProving37 extends AbstractProvingMDPAcrobot {

    public AcrobotProving37() {
        super();
        double p[] = {1.200000 , 0.080000 , 0.390203 , 0.221933 , 2.318169 , -1.985389 , 0.337634 , -0.086321 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        