
//package org.rlcommunity.environment.proving;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotProving26 extends AbstractProvingMDPAcrobot {

    public AcrobotProving26() {
        super();
        double p[] = {1.900000 , 0.040000 , 0.933565 , 0.484037 , 3.116346 , 0.641670 , 0.005578 , -0.418562 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        