
//package org.rlcommunity.environment.proving;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotProving18 extends AbstractProvingMDPAcrobot {

    public AcrobotProving18() {
        super();
        double p[] = {1.300000 , 0.020000 , 0.714022 , 0.806073 , -2.185655 , -2.998199 , 0.364460 , 0.034993 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        