
//package org.rlcommunity.environment.proving;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotProving13 extends AbstractProvingMDPAcrobot {

    public AcrobotProving13() {
        super();
        double p[] = {1.600000 , 0.060000 , 0.254403 , 0.155084 , -2.731508 , 2.661968 , 0.618882 , 0.465189 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        