
//package org.rlcommunity.environment.proving;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotProving50 extends AbstractProvingMDPAcrobot {

    public AcrobotProving50() {
        super();
        double p[] = {1.400000 , 0.060000 , 0.818534 , 0.227867 , -2.524960 , 2.781140 , 0.042748 , 0.329656 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        