
//package org.rlcommunity.environment.proving;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotProving19 extends AbstractProvingMDPAcrobot {

    public AcrobotProving19() {
        super();
        double p[] = {1.700000 , 0.070000 , 0.630119 , 0.426401 , -2.458417 , 1.228562 , -0.300931 , 0.709075 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        