
//package org.rlcommunity.environment.proving;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotProving12 extends AbstractProvingMDPAcrobot {

    public AcrobotProving12() {
        super();
        double p[] = {0.800000 , 0.030000 , 0.689012 , 0.349482 , -2.236815 , -2.946212 , -0.667653 , 0.244997 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        