
//package org.rlcommunity.environment.proving;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotProving8 extends AbstractProvingMDPAcrobot {

    public AcrobotProving8() {
        super();
        double p[] = {1.600000 , 0.040000 , 0.651253 , 0.450349 , -0.048216 , 0.396296 , -0.789699 , 0.371274 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        