
//package org.rlcommunity.environment.proving;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotProving41 extends AbstractProvingMDPAcrobot {

    public AcrobotProving41() {
        super();
        double p[] = {1.400000 , 0.020000 , 0.940418 , 0.957205 , 2.465338 , -0.779302 , -0.489470 , -0.835519 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        