
//package org.rlcommunity.environment.proving;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotProving17 extends AbstractProvingMDPAcrobot {

    public AcrobotProving17() {
        super();
        double p[] = {1.400000 , 0.060000 , 0.826515 , 0.209562 , -1.392096 , -2.236807 , -0.169081 , 0.311348 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        