
//package org.rlcommunity.environment.proving;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotProving1 extends AbstractProvingMDPAcrobot {

    public AcrobotProving1() {
        super();
        double p[] = {1.200000 , 0.020000 , 0.648857 , 0.918706 , 0.841970 , -2.598510 , -0.218654 , 0.170907 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        