
//package org.rlcommunity.environment.proving;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotProving47 extends AbstractProvingMDPAcrobot {

    public AcrobotProving47() {
        super();
        double p[] = {1.100000 , 0.040000 , 0.431257 , 0.309273 , -0.032574 , -0.082738 , -0.277442 , -0.368225 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        