
//package org.rlcommunity.environment.proving;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotProving46 extends AbstractProvingMDPAcrobot {

    public AcrobotProving46() {
        super();
        double p[] = {1.400000 , 0.030000 , 0.866399 , 0.176330 , 3.106464 , -2.967755 , 0.559730 , 0.202061 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        