
//package org.rlcommunity.environment.proving;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotProving34 extends AbstractProvingMDPAcrobot {

    public AcrobotProving34() {
        super();
        double p[] = {1.700000 , 0.050000 , 0.929690 , 0.285116 , 1.259036 , -2.829569 , 0.631626 , 0.764910 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        