
//package org.rlcommunity.environment.proving;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotProving5 extends AbstractProvingMDPAcrobot {

    public AcrobotProving5() {
        super();
        double p[] = {1.500000 , 0.040000 , 0.155745 , 0.595799 , -2.494370 , 1.573951 , -0.227665 , 0.627449 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        