
//package org.rlcommunity.environment.proving;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotProving40 extends AbstractProvingMDPAcrobot {

    public AcrobotProving40() {
        super();
        double p[] = {0.800000 , 0.010000 , 0.494540 , 0.854190 , -1.586728 , 0.437951 , -0.601600 , -0.455338 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        