
//package org.rlcommunity.environment.proving;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotProving42 extends AbstractProvingMDPAcrobot {

    public AcrobotProving42() {
        super();
        double p[] = {1.700000 , 0.060000 , 0.362119 , 0.117255 , 1.020455 , -0.288363 , 0.550977 , -0.105646 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        