
//package org.rlcommunity.environment.proving;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotProving15 extends AbstractProvingMDPAcrobot {

    public AcrobotProving15() {
        super();
        double p[] = {1.000000 , 0.080000 , 0.264888 , 0.612601 , -0.290341 , 0.692730 , 0.168207 , -0.497162 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        