
//package org.rlcommunity.environment.proving;
/*
 * This code was auto-generated by the MDP script. Do not change these values manually.
 */

import org.rlcommunity.environment.generalizedacrobot.AbstractProvingMDPAcrobot;

public class AcrobotProving22 extends AbstractProvingMDPAcrobot {

    public AcrobotProving22() {
        super();
        double p[] = {1.300000 , 0.050000 , 0.540729 , 0.895133 , 0.889193 , -2.621948 , 0.347402 , 0.296049 };
        setCompetition(true);
        setRandomStarts(true);
        setCompetitionParams( p );
        }
}
        