
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP44;

import GeneralizedHelicopter.*;

public class HPMDP44 extends AbstractProvingMDPHelicopter{

    public HPMDP44(){
	super();
        setWind0(0.650950d);
    	setWind1(-0.881746d);
    }
}