
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP17;

import GeneralizedHelicopter.*;

public class HPMDP17 extends AbstractProvingMDPHelicopter{

    public HPMDP17(){
	super();
        setWind0(0.679303d);
    	setWind1(0.384155d);
    }
}