
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP0;

import GeneralizedHelicopter.*;

public class HPMDP0 extends AbstractProvingMDPHelicopter{

    public HPMDP0(){
	super();
        setWind0(0.602084d);
    	setWind1(0.697216d);
    }
}