
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP11;

import GeneralizedHelicopter.*;

public class HPMDP11 extends AbstractProvingMDPHelicopter{

    public HPMDP11(){
	super();
        setWind0(-0.695378d);
    	setWind1(-0.579348d);
    }
}