
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP45;

import GeneralizedHelicopter.*;

public class HPMDP45 extends AbstractProvingMDPHelicopter{

    public HPMDP45(){
	super();
        setWind0(0.096449d);
    	setWind1(0.770099d);
    }
}