
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP68;

import GeneralizedHelicopter.*;

public class HPMDP68 extends AbstractProvingMDPHelicopter{

    public HPMDP68(){
	super();
        setWind0(-0.690825d);
    	setWind1(-0.518722d);
    }
}