
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP36;

import GeneralizedHelicopter.*;

public class HPMDP36 extends AbstractProvingMDPHelicopter{

    public HPMDP36(){
	super();
        setWind0(-0.687246d);
    	setWind1(0.898454d);
    }
}