
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP60;

import GeneralizedHelicopter.*;

public class HPMDP60 extends AbstractProvingMDPHelicopter{

    public HPMDP60(){
	super();
        setWind0(-0.066451d);
    	setWind1(0.696918d);
    }
}