
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP29;

import GeneralizedHelicopter.*;

public class HPMDP29 extends AbstractProvingMDPHelicopter{

    public HPMDP29(){
	super();
        setWind0(-0.375615d);
    	setWind1(0.192779d);
    }
}