
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP82;

import GeneralizedHelicopter.*;

public class HPMDP82 extends AbstractProvingMDPHelicopter{

    public HPMDP82(){
	super();
        setWind0(-0.591959d);
    	setWind1(0.525348d);
    }
}