
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP51;

import GeneralizedHelicopter.*;

public class HPMDP51 extends AbstractProvingMDPHelicopter{

    public HPMDP51(){
	super();
        setWind0(-0.266100d);
    	setWind1(-0.129304d);
    }
}