
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP99;

import GeneralizedHelicopter.*;

public class HPMDP99 extends AbstractProvingMDPHelicopter{

    public HPMDP99(){
	super();
        setWind0(-0.069014d);
    	setWind1(0.075972d);
    }
}