
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP86;

import GeneralizedHelicopter.*;

public class HPMDP86 extends AbstractProvingMDPHelicopter{

    public HPMDP86(){
	super();
        setWind0(-0.631646d);
    	setWind1(-0.004912d);
    }
}