
/*
 * This code was auto-generated by the parameter script. Do not change these values manually.
 */
package HPMDP91;

import GeneralizedHelicopter.*;

public class HPMDP91 extends AbstractProvingMDPHelicopter{

    public HPMDP91(){
	super();
        setWind0(0.289023d);
    	setWind1(-0.838460d);
    }
}